[package]
name = "services"
version = "0.1.0"
edition = "2021"


[dependencies]
entities = { path = "../entities" }
id-generator = { path = "../crates/id-generator" }
database = { path = "../database" }
casbin = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }
mongodb = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }
aes-gcm = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
regex = "1.12.3"

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
