[package]
name = "services"
version = "0.1.0"
edition = "2021"
autotests = false


[dependencies]
erp-sales = { workspace = true }
erp-procurement = { workspace = true }
erp-fulfillment = { workspace = true }
erp-returns = { workspace = true }
erp-finance = { workspace = true }
bpm = { workspace = true }
entities = { workspace = true }
entity-core = { workspace = true }
erp-core = { workspace = true }
application-core = { workspace = true }
async-trait = { workspace = true }
erp-identity = { workspace = true }
erp-audit = { workspace = true }
erp-workflow = { workspace = true }
erp-support = { workspace = true }
erp-party = { workspace = true }
erp-customer = { workspace = true }
erp-supplier = { workspace = true }
erp-catalog = { workspace = true }
erp-warehouse = { workspace = true }
erp-contract = { workspace = true }
erp-import = { workspace = true }
erp-inventory = { workspace = true }
id-generator = { workspace = true }
database = { workspace = true }
persistence-core = { workspace = true }
casbin = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
validator = { workspace = true }
mongodb = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }
aes-gcm = { workspace = true }
base64 = { workspace = true }
hmac = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
regex = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }

[dev-dependencies]
test-support = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
