// Generated by web-api/build.rs from identity audit_actions.rs. Do not edit.
export const AUDIT_ACTION_OPTIONS = [
    {
        value: "permission.create",
        label: "权限定义 · 新建",
    },
    {
        value: "permission.update",
        label: "权限定义 · 修改",
    },
    {
        value: "permission.delete",
        label: "权限定义 · 删除",
    },
    {
        value: "data_scope.create",
        label: "数据范围 · 新建",
    },
    {
        value: "data_scope.delete",
        label: "数据范围 · 删除",
    },
    {
        value: "user_role.assign",
        label: "用户角色 · 授权",
    },
    {
        value: "user_role.revoke",
        label: "用户角色 · 撤权",
    },
    {
        value: "person_query_qualification.change",
        label: "人员查询资格 · 维护",
    },
] as const
