// @generated by apps/web-api/build.rs. Do not edit.
export interface PermissionItem {
    module: string
    method: string
    path: string
    description: string
    permission: {
      resource: string
      action: string
    }
}

export interface PermissionGroup {
    name: string;
    description: string;
    permissions: PermissionItem[];
}

export const PERMISSION_GROUPS: PermissionGroup[] = [
    {
        name: "账号管理",
        description: "管理员账号的增删改查",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/admins",
                description: "查询管理员列表",
                permission: {
                    resource: "admin",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/admins",
                description: "创建管理员",
                permission: {
                    resource: "admin",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/admins/{id}",
                description: "更新管理员信息",
                permission: {
                    resource: "admin",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "DELETE",
                path: "/admin/admins/{id}",
                description: "删除管理员",
                permission: {
                    resource: "admin",
                    action: "delete",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/admins/{id}/role",
                description: "更新管理员角色",
                permission: {
                    resource: "admin",
                    action: "update_role",
                },
            },
        ],
    },
    {
        name: "角色管理",
        description: "系统角色和权限配置",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/roles",
                description: "查询角色列表",
                permission: {
                    resource: "role",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/roles/assignable",
                description: "查询可分配角色",
                permission: {
                    resource: "role",
                    action: "assignable_list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/roles",
                description: "创建角色",
                permission: {
                    resource: "role",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/roles/{id}",
                description: "更新角色信息",
                permission: {
                    resource: "role",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "DELETE",
                path: "/admin/roles/{id}",
                description: "删除角色",
                permission: {
                    resource: "role",
                    action: "delete",
                },
            },
        ],
    },
    {
        name: "系统审计",
        description: "系统操作日志",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/audit-logs",
                description: "查询审计日志",
                permission: {
                    resource: "audit_log",
                    action: "list",
                },
            },
        ],
    },
    {
        name: "来源注册",
        description: "来源系统与外部身份映射管理",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/source-systems",
                description: "查询来源系统列表",
                permission: {
                    resource: "source_system",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/source-systems",
                description: "创建来源系统",
                permission: {
                    resource: "source_system",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/source-systems/{id}",
                description: "更新来源系统",
                permission: {
                    resource: "source_system",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/external-identity-maps",
                description: "查询外部身份映射列表",
                permission: {
                    resource: "external_identity_map",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/external-identity-maps",
                description: "建立外部身份映射",
                permission: {
                    resource: "external_identity_map",
                    action: "create",
                },
            },
        ],
    },
    {
        name: "供应商订单",
        description: "供应商履约订单、动作与退款事实管理",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/supplier-fulfillment-orders",
                description: "查询供应商履约订单列表",
                permission: {
                    resource: "supplier_fulfillment_order",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-fulfillment-orders",
                description: "向供应商提交下单",
                permission: {
                    resource: "supplier_fulfillment_order",
                    action: "submit",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/supplier-fulfillment-orders/{id}",
                description: "查询供应商履约订单详情",
                permission: {
                    resource: "supplier_fulfillment_order",
                    action: "detail",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-fulfillment-orders/{id}/cancel",
                description: "向供应商提交取消",
                permission: {
                    resource: "supplier_fulfillment_order",
                    action: "cancel",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-fulfillment-orders/{id}/refund",
                description: "向供应商提交退款",
                permission: {
                    resource: "supplier_fulfillment_order",
                    action: "refund",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-fulfillment-orders/{id}/reject",
                description: "登记供应商拒单结果",
                permission: {
                    resource: "supplier_fulfillment_order",
                    action: "reject",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-refund-facts",
                description: "登记供应商退款成功结果",
                permission: {
                    resource: "supplier_refund_fact",
                    action: "post",
                },
            },
        ],
    },
    {
        name: "供应商结算",
        description: "供应商周期结算单、明细与差异管理",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/supplier-settlement-statements",
                description: "查询供应商结算单列表",
                permission: {
                    resource: "supplier_settlement_statement",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-settlement-statements",
                description: "创建供应商结算草稿",
                permission: {
                    resource: "supplier_settlement_statement",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/supplier-settlement-statements/{id}",
                description: "查询供应商结算单详情",
                permission: {
                    resource: "supplier_settlement_statement",
                    action: "detail",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-settlement-statements/{id}/submit-review",
                description: "提交结算复核",
                permission: {
                    resource: "supplier_settlement_statement",
                    action: "submit",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-settlement-statements/{id}/confirm",
                description: "确认结算并形成应付",
                permission: {
                    resource: "supplier_settlement_statement",
                    action: "confirm",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-settlement-statements/{id}/void",
                description: "作废结算单",
                permission: {
                    resource: "supplier_settlement_statement",
                    action: "void",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/supplier-settlement-items",
                description: "查询供应商结算明细列表",
                permission: {
                    resource: "supplier_settlement_item",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/supplier-settlement-differences",
                description: "查询供应商结算差异列表",
                permission: {
                    resource: "supplier_settlement_difference",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/supplier-settlement-differences/{id}/resolve",
                description: "登记结算差异处理结论",
                permission: {
                    resource: "supplier_settlement_difference",
                    action: "update",
                },
            },
        ],
    },
];
