/** globals.css 自定义字号的类合并注册名；取值仅由全局主题定义。 */
export const themeTextNames = [
    "2xs",
    "tiny",
    "body-compact",
    "page-title",
    "value-summary",
    "value-hero",
    "login-title",
] as const

/** globals.css 自定义尺寸的类合并注册名；新增尺寸须同步登记。 */
export const themeSpacingNames = [
    "topbar",
    "control-xs",
    "control-sm",
    "control",
    "control-lg",
    "page-inline",
    "page-inline-lg",
    "page-block",
    "page-block-lg",
    "workspace-inline",
    "workspace-block-start-lg",
    "workspace-header-block-end",
    "workspace-toolbar-block",
    "workspace-view",
    "workspace-view-gap",
    "toolbar-inset",
    "search-min",
    "row",
    "row-comfortable",
    "table-header",
    "table-header-block",
    "table-cell-inline",
    "table-cell-block",
    "table-cell-block-comfortable",
    "table-frame-inset",
    "table-resize-target",
    "table-column-default",
    "table-column-default-min",
    "table-column-selection",
    "table-column-preview",
    "table-column-reference",
    "table-column-reference-min",
    "table-column-status",
    "table-column-status-min",
    "table-column-amount",
    "table-column-amount-min",
    "table-column-quantity",
    "table-column-quantity-min",
    "table-column-rate",
    "table-column-rate-min",
    "table-column-tracks",
    "table-column-tracks-min",
    "nav",
    "nav-icon",
    "nav-mobile",
    "preview",
    "detail",
    "shell",
    "object-tab",
] as const
