[package]
name = "id-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
mongodb = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
database = { path = "../../database" }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
