[package]
name = "web-api"
version = "0.1.0"
edition = "2021"
autotests = false


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true, features = ["macros"] }
chrono = { workspace = true }
jwt-hmac = { workspace = true }
jwt = { workspace = true }

mongodb = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
  "macros",
  "sync",
  "time",
  "rt-multi-thread",
  "net",
  "signal",
] }
tower = { workspace = true }
tower-http = { workspace = true }
validator = { workspace = true }
jwt-sha2 = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

storage = { workspace = true }
id-generator = { workspace = true }
database = { workspace = true }
persistence-core = { workspace = true }
entities = { workspace = true }
erp-core = { workspace = true }
application-core = { workspace = true }
erp-identity = { workspace = true }
erp-audit = { workspace = true }
erp-workflow = { workspace = true }
erp-processes = { workspace = true }
erp-read-models = { workspace = true }
erp-support = { workspace = true }
erp-party = { workspace = true }
erp-customer = { workspace = true }
erp-supplier = { workspace = true }
erp-catalog = { workspace = true }
erp-warehouse = { workspace = true }
erp-contract = { workspace = true }
erp-import = { workspace = true }
services = { workspace = true }
config = { workspace = true }
permission-macros = { workspace = true }

[build-dependencies]
syn = { workspace = true, features = ["full"] }

[dev-dependencies]
test-support = { workspace = true }
