#!/usr/bin/env bash
# Build, push, and record one immutable rs-project-template backend image release.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RELEASE_DIR="${RS_PROJECT_TEMPLATE_RELEASE_OUTPUT_DIR:-$ROOT_DIR/releases}"
TAG="${RS_PROJECT_TEMPLATE_RELEASE_TAG:-$(git -C "$ROOT_DIR" rev-parse --verify HEAD)}"

usage() {
  cat >&2 <<'EOF'
usage: scripts/release-image.sh <build|push>

Required environment:
  RS_PROJECT_TEMPLATE_BACKEND_IMAGE_REPOSITORY

Optional:
  RS_PROJECT_TEMPLATE_RELEASE_TAG
  RS_PROJECT_TEMPLATE_RELEASE_OUTPUT_DIR
EOF
}

require_env() {
  local variable
  for variable in \
    RS_PROJECT_TEMPLATE_BACKEND_IMAGE_REPOSITORY
  do
    if [[ -z "${!variable:-}" ]]; then
      echo "missing required environment: $variable" >&2
      exit 2
    fi
  done
  if [[ ! "$TAG" =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "release tag contains unsupported characters: $TAG" >&2
    exit 2
  fi
}

image_ref() {
  printf '%s:%s' "$1" "$TAG"
}

backend_image="$(image_ref "${RS_PROJECT_TEMPLATE_BACKEND_IMAGE_REPOSITORY:-}")"

build() {
  docker build \
    --pull \
    --target runtime \
    --tag "$backend_image" \
    "$ROOT_DIR"
}

digest_ref() {
  local repository="$1" image digest
  image="$(image_ref "$repository")"
  digest="$(
    docker image inspect \
      --format '{{range .RepoDigests}}{{println .}}{{end}}' \
      "$image" |
      awk -v prefix="$repository@sha256:" \
        'index($0, prefix) == 1 { print; exit }'
  )"
  if [[ -z "$digest" ]]; then
    echo "registry digest unavailable after pushing $image" >&2
    exit 1
  fi
  printf '%s' "$digest"
}

push() {
  mkdir -p "$RELEASE_DIR"
  docker push "$backend_image"

  local manifest="$RELEASE_DIR/$TAG.env"
  umask 077
  {
    printf '%s\n' '# Generated by scripts/release-image.sh; do not edit image digests.'
    printf 'RS_PROJECT_TEMPLATE_RELEASE_TAG=%s\n' "$TAG"
    printf 'RS_PROJECT_TEMPLATE_GIT_COMMIT=%s\n' "$(git -C "$ROOT_DIR" rev-parse HEAD)"
    printf 'RS_PROJECT_TEMPLATE_BACKEND_IMAGE=%s\n' \
      "$(digest_ref "$RS_PROJECT_TEMPLATE_BACKEND_IMAGE_REPOSITORY")"
  } >"$manifest"
  echo "deployable release manifest: $manifest"
}

case "${1:-}" in
  build)
    require_env
    build
    ;;
  push)
    require_env
    push
    ;;
  *)
    usage
    exit 2
    ;;
esac
