#!/usr/bin/env bash
# Deploy or roll back a digest-pinned rs-project-template release manifest.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COMPOSE_FILE="${RS_PROJECT_TEMPLATE_PRODUCTION_COMPOSE_FILE:-$ROOT_DIR/docker-compose.production.yml}"
STATE_DIR="${RS_PROJECT_TEMPLATE_RELEASE_STATE_DIR:-$ROOT_DIR/.release-state}"
LOCK_DIR="$STATE_DIR/.lock"

usage() {
  cat >&2 <<'EOF'
usage:
  scripts/release-deploy.sh deploy <release-manifest.env>
  scripts/release-deploy.sh rollback <release-tag>
  scripts/release-deploy.sh current

The release manifest must contain a digest-pinned backend image
generated by scripts/release-image.sh.
EOF
}

acquire_lock() {
  mkdir -p "$STATE_DIR"
  if ! mkdir "$LOCK_DIR" 2>/dev/null; then
    echo "another release operation is already running: $LOCK_DIR" >&2
    exit 1
  fi
  trap 'rmdir "$LOCK_DIR"' EXIT
}

manifest_value() {
  local manifest="$1" key="$2"
  sed -n "s/^${key}=//p" "$manifest" | tail -n 1
}

validate_manifest() {
  local manifest="$1" key value tag
  [[ -f "$manifest" ]] || {
    echo "manifest not found: $manifest" >&2
    exit 2
  }
  for key in \
    RS_PROJECT_TEMPLATE_RELEASE_TAG \
    RS_PROJECT_TEMPLATE_GIT_COMMIT \
    RS_PROJECT_TEMPLATE_BACKEND_IMAGE
  do
    value="$(manifest_value "$manifest" "$key")"
    [[ -n "$value" ]] || {
      echo "manifest lacks $key: $manifest" >&2
      exit 2
    }
  done
  for key in \
    RS_PROJECT_TEMPLATE_BACKEND_IMAGE
  do
    value="$(manifest_value "$manifest" "$key")"
    [[ "$value" =~ ^[^[:space:]@]+@sha256:[0-9a-f]{64}$ ]] || {
      echo "manifest image must be digest-pinned: $key" >&2
      exit 2
    }
  done
  tag="$(manifest_value "$manifest" RS_PROJECT_TEMPLATE_RELEASE_TAG)"
  [[ "$tag" =~ ^[A-Za-z0-9._-]+$ ]] || {
    echo "unsafe release tag: $tag" >&2
    exit 2
  }
}

prepare_host_paths() {
  local config_file="${RS_PROJECT_TEMPLATE_CONFIG_FILE:-$ROOT_DIR/config.toml}"
  if [[ "$config_file" != /* ]]; then
    config_file="$ROOT_DIR/$config_file"
  fi
  [[ -f "$config_file" ]] || {
    echo "production config is missing: $config_file" >&2
    exit 2
  }
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "deployment must run as root to protect config and writable paths" >&2
    exit 2
  fi

  chown root:root "$config_file"
  chmod 0640 "$config_file"
  mkdir -p "$ROOT_DIR/uploads"
  chown root:root "$ROOT_DIR/uploads"
  chmod 2770 "$ROOT_DIR/uploads"
}

run_compose() {
  local manifest="$1"
  shift
  docker compose --env-file "$manifest" -f "$COMPOSE_FILE" "$@"
}

wait_for_service_command() {
  local manifest="$1" service="$2" description="$3"
  shift 3
  local attempt
  for ((attempt = 1; attempt <= 60; attempt++)); do
    if run_compose "$manifest" exec -T "$service" "$@" >/dev/null 2>&1; then
      printf '%s is ready\n' "$description"
      return 0
    fi
    sleep 2
  done
  echo "timed out waiting for $description" >&2
  run_compose "$manifest" ps >&2 || true
  run_compose "$manifest" logs --tail 100 "$service" >&2 || true
  return 1
}

verify_release() {
  local manifest="$1"
  wait_for_service_command "$manifest" web-api "Web API health" \
    curl --fail --silent --show-error --max-time 3 \
    http://127.0.0.1:10001/health
}

restore_previous_release() {
  local previous="$1" previous_manifest
  [[ "$previous" =~ ^releases/[A-Za-z0-9._-]+\.env$ ]] || {
    echo "previous release link is unsafe; automatic rollback skipped: $previous" >&2
    return 1
  }
  previous_manifest="$STATE_DIR/$previous"
  validate_manifest "$previous_manifest"
  echo "restoring previous release from $previous_manifest" >&2
  run_compose "$previous_manifest" pull
  run_compose "$previous_manifest" up -d --no-build
  verify_release "$previous_manifest"
}

deploy() {
  local source_manifest="$1" tag commit stored_manifest previous
  validate_manifest "$source_manifest"
  prepare_host_paths

  tag="$(manifest_value "$source_manifest" RS_PROJECT_TEMPLATE_RELEASE_TAG)"
  commit="$(manifest_value "$source_manifest" RS_PROJECT_TEMPLATE_GIT_COMMIT)"
  stored_manifest="$STATE_DIR/releases/$tag.env"
  mkdir -p "$STATE_DIR/releases"
  if [[ "$source_manifest" != "$stored_manifest" ]]; then
    cp "$source_manifest" "$stored_manifest"
  fi

  previous="$(readlink "$STATE_DIR/current.env" 2>/dev/null || true)"
  run_compose "$stored_manifest" config --quiet
  run_compose "$stored_manifest" pull
  if ! run_compose "$stored_manifest" \
    run --rm --no-deps --entrypoint sh web-api \
    -c 'test -r /app/config.toml && test -w /app/uploads'
  then
    echo "backend container user cannot access config/log/upload paths" >&2
    exit 1
  fi

  run_compose "$stored_manifest" up -d --no-build
  if ! verify_release "$stored_manifest"; then
    if [[ -n "$previous" ]] && restore_previous_release "$previous"; then
      echo "new release failed health checks; previous release restored" >&2
      printf '%s failed_tag=%s restored=%s\n' \
        "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        "$tag" \
        "$previous" \
        >>"$STATE_DIR/deployments.log"
    else
      echo "new release failed health checks and automatic rollback was unavailable" >&2
    fi
    return 1
  fi

  ln -sfn "releases/$tag.env" "$STATE_DIR/current.env"
  printf '%s tag=%s commit=%s previous=%s\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    "$tag" \
    "$commit" \
    "${previous:-none}" \
    >>"$STATE_DIR/deployments.log"
  printf 'deployed release %s (previous manifest: %s)\n' \
    "$tag" \
    "${previous:-none}"
}

rollback() {
  local tag="$1" manifest
  [[ "$tag" =~ ^[A-Za-z0-9._-]+$ ]] || {
    echo "unsafe release tag: $tag" >&2
    exit 2
  }
  manifest="$STATE_DIR/releases/$tag.env"
  deploy "$manifest"
  printf 'rolled back to %s\n' "$tag"
}

acquire_lock
case "${1:-}" in
  deploy)
    [[ $# -eq 2 ]] || {
      usage
      exit 2
    }
    deploy "$2"
    ;;
  rollback)
    [[ $# -eq 2 ]] || {
      usage
      exit 2
    }
    rollback "$2"
    ;;
  current)
    readlink "$STATE_DIR/current.env" || true
    ;;
  *)
    usage
    exit 2
    ;;
esac
