//! Domain-owned MongoDB repositories composed from persistence-core.

mod business_capability_confirmation;
mod contract;
mod contract_revision;
mod cost_allocation;
mod cost_entry;
mod customer_acceptance;
mod customer_receipt;
mod customer_refund;
mod delivery;
mod electronic_delivery;
mod inbox_message;
mod integration_error_task;
mod invoice;
mod legacy_import_batch;
mod legacy_import_confirmation;
mod legacy_import_row;
mod payable_account;
mod payable_entry;
mod payable_entry_offset;
mod payment_allocation;
mod payment_reversal;
mod procurement_responsibility_rule;
mod product;
mod product_brand;
mod product_category;
mod product_category_attribute;
mod product_revision;
mod product_revision_media;
mod purchase_change_order;
mod purchase_change_submission;
mod purchase_change_submission_line;
mod purchase_invoice_allocation;
mod purchase_line_sales_allocation;
mod purchase_order;
mod purchase_order_revision;
mod purchase_order_revision_line;
mod purchase_order_submission;
mod purchase_order_submission_line;
mod purchase_receipt;
mod purchase_return_line;
mod purchase_return_order;
mod receipt_allocation;
mod receipt_reversal;
mod receivable_account;
mod receivable_entry;
mod receivable_entry_offset;
mod receivable_funds_review;
mod reconciliation_difference;
mod reconciliation_difference_resolution;
mod sales_change_order;
mod sales_change_submission;
mod sales_change_submission_line;
mod sales_invoice_allocation;
mod sales_order;
mod sales_order_goods_service_line_revision;
mod sales_order_line;
mod sales_order_revision;
mod sales_order_revision_line;
mod sales_order_submission;
mod sales_order_submission_line;
mod sales_order_voucher_line_revision;
mod sales_order_working_copy;
mod sales_order_working_copy_line;
mod sales_return_case;
mod sales_return_line;
mod service_fulfillment;
mod sku;
mod sku_attribute;
mod sku_attribute_value;
mod sku_revision;
mod stock_adjustment;
mod stock_adjustment_line;
mod stock_balance;
mod stock_movement;
mod stock_reservation;
mod supplier_api_capability;
mod supplier_api_connection;
mod supplier_connection_command_receipt;
mod supplier_fulfillment_item;
mod supplier_fulfillment_order;
mod supplier_health_check_run;
mod supplier_offering;
mod supplier_offering_availability;
mod supplier_offering_command;
mod supplier_offering_revision;
mod supplier_order_action;
mod supplier_order_action_line;
mod supplier_order_status_history;
mod supplier_payment;
mod supplier_refund;
mod supplier_refund_allocation;
mod supplier_refund_fact;
mod supplier_settlement_difference;
mod supplier_settlement_difference_evidence;
mod supplier_settlement_item;
mod supplier_settlement_source_evidence;
mod supplier_settlement_statement;
mod unit_of_measure;
mod voucher_category_profile_revision;
mod warehouse;
mod warehouse_revision;
mod warehouse_sku_policy;

pub use business_capability_confirmation::BusinessCapabilityConfirmationRepository;
pub use contract::ContractRepository;
pub use contract_revision::ContractRevisionRepository;
pub use cost_allocation::CostAllocationRepository;
pub use cost_entry::CostEntryRepository;
pub use customer_acceptance::CustomerAcceptanceRepository;
pub use customer_receipt::CustomerReceiptRepository;
pub use customer_refund::CustomerRefundRepository;
pub use delivery::DeliveryRepository;
pub use electronic_delivery::ElectronicDeliveryRepository;
pub use inbox_message::InboxMessageRepository;
pub use integration_error_task::IntegrationErrorTaskRepository;
pub use invoice::InvoiceRepository;
pub use legacy_import_batch::LegacyImportBatchRepository;
pub use legacy_import_confirmation::LegacyImportConfirmationRepository;
pub use legacy_import_row::LegacyImportRowRepository;
pub use payable_account::PayableAccountRepository;
pub use payable_entry::PayableEntryRepository;
pub use payable_entry_offset::PayableEntryOffsetRepository;
pub use payment_allocation::PaymentAllocationRepository;
pub use payment_reversal::PaymentReversalRepository;
pub use procurement_responsibility_rule::ProcurementResponsibilityRuleRepository;
pub use product::ProductRepository;
pub use product_brand::ProductBrandRepository;
pub use product_category::ProductCategoryRepository;
pub use product_category_attribute::ProductCategoryAttributeRepository;
pub use product_revision::ProductRevisionRepository;
pub use product_revision_media::ProductRevisionMediaRepository;
pub use purchase_change_order::PurchaseChangeOrderRepository;
pub use purchase_change_submission::PurchaseChangeSubmissionRepository;
pub use purchase_change_submission_line::PurchaseChangeSubmissionLineRepository;
pub use purchase_invoice_allocation::PurchaseInvoiceAllocationRepository;
pub use purchase_line_sales_allocation::PurchaseLineSalesAllocationRepository;
pub use purchase_order::PurchaseOrderRepository;
pub use purchase_order_revision::PurchaseOrderRevisionRepository;
pub use purchase_order_revision_line::PurchaseOrderRevisionLineRepository;
pub use purchase_order_submission::PurchaseOrderSubmissionRepository;
pub use purchase_order_submission_line::PurchaseOrderSubmissionLineRepository;
pub use purchase_receipt::PurchaseReceiptRepository;
pub use purchase_return_line::PurchaseReturnLineRepository;
pub use purchase_return_order::PurchaseReturnOrderRepository;
pub use receipt_allocation::ReceiptAllocationRepository;
pub use receipt_reversal::ReceiptReversalRepository;
pub use receivable_account::ReceivableAccountRepository;
pub use receivable_entry::ReceivableEntryRepository;
pub use receivable_entry_offset::ReceivableEntryOffsetRepository;
pub use receivable_funds_review::ReceivableFundsReviewRepository;
pub use reconciliation_difference::ReconciliationDifferenceRepository;
pub use reconciliation_difference_resolution::ReconciliationDifferenceResolutionRepository;
pub use sales_change_order::SalesChangeOrderRepository;
pub use sales_change_submission::SalesChangeSubmissionRepository;
pub use sales_change_submission_line::SalesChangeSubmissionLineRepository;
pub use sales_invoice_allocation::SalesInvoiceAllocationRepository;
pub use sales_order::SalesOrderRepository;
pub use sales_order_goods_service_line_revision::SalesOrderGoodsServiceLineRevisionRepository;
pub use sales_order_line::SalesOrderLineRepository;
pub use sales_order_revision::SalesOrderRevisionRepository;
pub use sales_order_revision_line::SalesOrderRevisionLineRepository;
pub use sales_order_submission::SalesOrderSubmissionRepository;
pub use sales_order_submission_line::SalesOrderSubmissionLineRepository;
pub use sales_order_voucher_line_revision::SalesOrderVoucherLineRevisionRepository;
pub use sales_order_working_copy::SalesOrderWorkingCopyRepository;
pub use sales_order_working_copy_line::SalesOrderWorkingCopyLineRepository;
pub use sales_return_case::SalesReturnCaseRepository;
pub use sales_return_line::SalesReturnLineRepository;
pub use service_fulfillment::ServiceFulfillmentRepository;
pub use sku::SkuRepository;
pub use sku_attribute::SkuAttributeRepository;
pub use sku_attribute_value::SkuAttributeValueRepository;
pub use sku_revision::SkuRevisionRepository;
pub use stock_adjustment::StockAdjustmentRepository;
pub use stock_adjustment_line::StockAdjustmentLineRepository;
pub use stock_balance::StockBalanceRepository;
pub use stock_movement::StockMovementRepository;
pub use stock_reservation::StockReservationRepository;
pub use supplier_api_capability::SupplierApiCapabilityRepository;
pub use supplier_api_connection::SupplierApiConnectionRepository;
pub use supplier_connection_command_receipt::SupplierConnectionCommandReceiptRepository;
pub use supplier_fulfillment_item::SupplierFulfillmentItemRepository;
pub use supplier_fulfillment_order::SupplierFulfillmentOrderRepository;
pub use supplier_health_check_run::SupplierHealthCheckRunRepository;
pub use supplier_offering::SupplierOfferingRepository;
pub use supplier_offering_availability::SupplierOfferingAvailabilityRepository;
pub use supplier_offering_command::SupplierOfferingCommandRepository;
pub use supplier_offering_revision::SupplierOfferingRevisionRepository;
pub use supplier_order_action::SupplierOrderActionRepository;
pub use supplier_order_action_line::SupplierOrderActionLineRepository;
pub use supplier_order_status_history::SupplierOrderStatusHistoryRepository;
pub use supplier_payment::SupplierPaymentRepository;
pub use supplier_refund::SupplierRefundRepository;
pub use supplier_refund_allocation::SupplierRefundAllocationRepository;
pub use supplier_refund_fact::SupplierRefundFactRepository;
pub use supplier_settlement_difference::SupplierSettlementDifferenceRepository;
pub use supplier_settlement_difference_evidence::SupplierSettlementDifferenceEvidenceRepository;
pub use supplier_settlement_item::SupplierSettlementItemRepository;
pub use supplier_settlement_source_evidence::SupplierSettlementSourceEvidenceRepository;
pub use supplier_settlement_statement::SupplierSettlementStatementRepository;
pub use unit_of_measure::UnitOfMeasureRepository;
pub use voucher_category_profile_revision::VoucherCategoryProfileRevisionRepository;
pub use warehouse::WarehouseRepository;
pub use warehouse_revision::WarehouseRevisionRepository;
pub use warehouse_sku_policy::WarehouseSkuPolicyRepository;
