//! Domain-owned MongoDB repositories composed from persistence-core.

mod business_capability_confirmation;

mod supplier_api_capability;
mod supplier_api_connection;
mod supplier_connection_command_receipt;
mod supplier_fulfillment_item;
mod supplier_fulfillment_order;
mod supplier_health_check_run;
mod supplier_offering;
mod supplier_offering_availability;
mod supplier_offering_command;
mod supplier_offering_revision;
mod supplier_order_action;
mod supplier_order_action_line;
mod supplier_order_status_history;
mod supplier_refund_allocation;
mod supplier_refund_fact;
mod supplier_settlement_difference;
mod supplier_settlement_difference_evidence;
mod supplier_settlement_item;
mod supplier_settlement_source_evidence;
mod supplier_settlement_statement;
pub use business_capability_confirmation::BusinessCapabilityConfirmationRepository;

pub use supplier_api_capability::SupplierApiCapabilityRepository;
pub use supplier_api_connection::SupplierApiConnectionRepository;
pub use supplier_connection_command_receipt::SupplierConnectionCommandReceiptRepository;
pub use supplier_fulfillment_item::SupplierFulfillmentItemRepository;
pub use supplier_fulfillment_order::SupplierFulfillmentOrderRepository;
pub use supplier_health_check_run::SupplierHealthCheckRunRepository;
pub use supplier_offering::SupplierOfferingRepository;
pub use supplier_offering_availability::SupplierOfferingAvailabilityRepository;
pub use supplier_offering_command::SupplierOfferingCommandRepository;
pub use supplier_offering_revision::SupplierOfferingRevisionRepository;
pub use supplier_order_action::SupplierOrderActionRepository;
pub use supplier_order_action_line::SupplierOrderActionLineRepository;
pub use supplier_order_status_history::SupplierOrderStatusHistoryRepository;
pub use supplier_refund_allocation::SupplierRefundAllocationRepository;
pub use supplier_refund_fact::SupplierRefundFactRepository;
pub use supplier_settlement_difference::SupplierSettlementDifferenceRepository;
pub use supplier_settlement_difference_evidence::SupplierSettlementDifferenceEvidenceRepository;
pub use supplier_settlement_item::SupplierSettlementItemRepository;
pub use supplier_settlement_source_evidence::SupplierSettlementSourceEvidenceRepository;
pub use supplier_settlement_statement::SupplierSettlementStatementRepository;
