// @generated by apps/web-api/build.rs. Do not edit.
export interface PermissionItem {
    module: string
    method: string
    path: string
    description: string
    permission: {
      resource: string
      action: string
    }
}

export interface PermissionGroup {
    name: string;
    description: string;
    permissions: PermissionItem[];
}

export const PERMISSION_GROUPS: PermissionGroup[] = [
    {
        name: "账号管理",
        description: "管理员账号的增删改查",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/admins",
                description: "查询管理员列表",
                permission: {
                    resource: "admin",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/admins",
                description: "创建管理员",
                permission: {
                    resource: "admin",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/admins/{id}",
                description: "更新管理员信息",
                permission: {
                    resource: "admin",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "DELETE",
                path: "/admin/admins/{id}",
                description: "删除管理员",
                permission: {
                    resource: "admin",
                    action: "delete",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/admins/{id}/role",
                description: "更新管理员角色",
                permission: {
                    resource: "admin",
                    action: "update_role",
                },
            },
        ],
    },
    {
        name: "角色管理",
        description: "系统角色和权限配置",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/roles",
                description: "查询角色列表",
                permission: {
                    resource: "role",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/roles/assignable",
                description: "查询可分配角色",
                permission: {
                    resource: "role",
                    action: "assignable_list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/roles",
                description: "创建角色",
                permission: {
                    resource: "role",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/roles/{id}",
                description: "更新角色信息",
                permission: {
                    resource: "role",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "DELETE",
                path: "/admin/roles/{id}",
                description: "删除角色",
                permission: {
                    resource: "role",
                    action: "delete",
                },
            },
        ],
    },
    {
        name: "系统审计",
        description: "系统操作日志",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/audit-logs",
                description: "查询审计日志",
                permission: {
                    resource: "audit_log",
                    action: "list",
                },
            },
        ],
    },
];
