apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-api
  labels:
    app.kubernetes.io/name: web-api
    app.kubernetes.io/part-of: erp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: erp-client
  labels:
    app.kubernetes.io/name: erp-client
    app.kubernetes.io/part-of: erp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: erp-client
