[package]
name = "storage"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }

[dev-dependencies]
aws-smithy-http-client = { workspace = true, features = ["test-util"] }
tokio = { workspace = true, features = ["macros", "rt"] }
