// @generated by apps/web-api/build.rs. Do not edit.
import type { PermissionItem } from "@/types/admin";

export interface PermissionGroup {
    name: string;
    description: string;
    permissions: PermissionItem[];
}

export const PERMISSION_GROUPS: PermissionGroup[] = [
    {
        name: "账号管理",
        description: "管理员账号的增删改查",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/admins",
                description: "查询管理员列表",
                permission: {
                    resource: "admin",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/admins",
                description: "创建管理员",
                permission: {
                    resource: "admin",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/admins/{id}",
                description: "更新管理员信息",
                permission: {
                    resource: "admin",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "DELETE",
                path: "/admin/admins/{id}",
                description: "删除管理员",
                permission: {
                    resource: "admin",
                    action: "delete",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/admins/{id}/role",
                description: "更新管理员角色",
                permission: {
                    resource: "admin",
                    action: "update_role",
                },
            },
        ],
    },
    {
        name: "角色管理",
        description: "系统角色和权限配置",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/roles",
                description: "查询角色列表",
                permission: {
                    resource: "role",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/roles/assignable",
                description: "查询可分配角色",
                permission: {
                    resource: "role",
                    action: "assignable_list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/roles",
                description: "创建角色",
                permission: {
                    resource: "role",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/roles/{id}",
                description: "更新角色信息",
                permission: {
                    resource: "role",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "DELETE",
                path: "/admin/roles/{id}",
                description: "删除角色",
                permission: {
                    resource: "role",
                    action: "delete",
                },
            },
        ],
    },
    {
        name: "系统审计",
        description: "系统操作日志",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/audit-logs",
                description: "查询审计日志",
                permission: {
                    resource: "audit_log",
                    action: "list",
                },
            },
        ],
    },
    {
        name: "来源注册",
        description: "来源系统与外部身份映射管理",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/source-systems",
                description: "查询来源系统列表",
                permission: {
                    resource: "source_system",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/source-systems",
                description: "创建来源系统",
                permission: {
                    resource: "source_system",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "PUT",
                path: "/admin/source-systems/{id}",
                description: "更新来源系统",
                permission: {
                    resource: "source_system",
                    action: "update",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/external-identity-maps",
                description: "查询外部身份映射列表",
                permission: {
                    resource: "external_identity_map",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/external-identity-maps",
                description: "建立外部身份映射",
                permission: {
                    resource: "external_identity_map",
                    action: "create",
                },
            },
        ],
    },
    {
        name: "集成治理",
        description: "入站消息、错误任务与对账差异（W29）",
        permissions: [
            {
                module: "admin",
                method: "GET",
                path: "/admin/integration/inbox-messages",
                description: "查询入站消息列表",
                permission: {
                    resource: "inbox_message",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/inbox-messages",
                description: "登记入站消息",
                permission: {
                    resource: "inbox_message",
                    action: "register",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/integration/inbox-messages/{id}",
                description: "查询入站消息详情",
                permission: {
                    resource: "inbox_message",
                    action: "detail",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/inbox-messages/{id}/result",
                description: "回写入站消息处理结果",
                permission: {
                    resource: "inbox_message",
                    action: "writeback",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/integration/error-tasks",
                description: "查询集成错误任务列表",
                permission: {
                    resource: "integration_error_task",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks",
                description: "登记集成错误任务",
                permission: {
                    resource: "integration_error_task",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/integration/error-tasks/{id}",
                description: "查询集成错误任务详情",
                permission: {
                    resource: "integration_error_task",
                    action: "detail",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks/{id}/query",
                description: "查询原结果",
                permission: {
                    resource: "integration_error_task",
                    action: "query",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks/{id}/replay",
                description: "重放原动作",
                permission: {
                    resource: "integration_error_task",
                    action: "replay",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks/{id}/hold",
                description: "暂挂或跳过当前任务",
                permission: {
                    resource: "integration_error_task",
                    action: "hold",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks/{id}/transfer",
                description: "转交集成错误任务",
                permission: {
                    resource: "integration_error_task",
                    action: "transfer",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks/{id}/resolve",
                description: "解决集成错误任务",
                permission: {
                    resource: "integration_error_task",
                    action: "resolve",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/error-tasks/{id}/close",
                description: "关闭集成错误任务",
                permission: {
                    resource: "integration_error_task",
                    action: "close",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/integration/differences",
                description: "查询对账差异列表",
                permission: {
                    resource: "reconciliation_difference",
                    action: "list",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/differences",
                description: "登记对账差异",
                permission: {
                    resource: "reconciliation_difference",
                    action: "create",
                },
            },
            {
                module: "admin",
                method: "GET",
                path: "/admin/integration/differences/{id}",
                description: "查询对账差异详情",
                permission: {
                    resource: "reconciliation_difference",
                    action: "detail",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/differences/{id}/process",
                description: "人工处理对账差异",
                permission: {
                    resource: "reconciliation_difference",
                    action: "process",
                },
            },
            {
                module: "admin",
                method: "POST",
                path: "/admin/integration/differences/{id}/resolve",
                description: "解决对账差异",
                permission: {
                    resource: "reconciliation_difference",
                    action: "resolve",
                },
            },
        ],
    },
];
