import { chromium } from "@playwright/test"
const OUT = "/private/tmp/claude-501/-Users-huangjiajiang-Development-erp/fda94318-8842-42d7-bbfe-c5956adaaa39/scratchpad"
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } })
const page = await ctx.newPage()
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message.slice(0,160)))
await page.goto("http://localhost:3000/login")
await page.getByPlaceholder("请输入账号").fill("admin")
await page.getByPlaceholder("请输入密码").fill("123456")
await page.getByRole("button", { name: "登录" }).click()
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 30000 })
await page.waitForTimeout(1200)
// 旧链接兼容
await page.goto("http://localhost:3000/system/access-audit?view=audit&actorId=a1")
await page.waitForTimeout(3500)
console.log("legacy redirect ->", page.url())
await page.goto("http://localhost:3000/system/access-audit?view=roles")
await page.waitForTimeout(4000)
await page.screenshot({ path: `${OUT}/21-final-roles.png` })
await page.goto("http://localhost:3000/system/roles/role-finance/edit")
await page.waitForTimeout(5000)
await page.screenshot({ path: `${OUT}/22-final-role-form.png` })
console.log("done")
await browser.close()
