import { chromium } from "@playwright/test"
const OUT = "/private/tmp/claude-501/-Users-huangjiajiang-Development-erp/fda94318-8842-42d7-bbfe-c5956adaaa39/scratchpad"
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1100 } })
const page = await ctx.newPage()
await page.goto("http://localhost:3000/login")
await page.getByPlaceholder("请输入账号").fill("admin")
await page.getByPlaceholder("请输入密码").fill("123456")
await page.getByRole("button", { name: "登录" }).click()
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 30000 })
await page.waitForTimeout(2500)
const links = await page.locator("a[href^='/']").allTextContents()
console.log("nav:", links.filter(Boolean).map(s=>s.trim()).join(" | "))
// 滚到系统分组
const sys = page.getByRole("link", { name: "权限配置" })
await sys.scrollIntoViewIfNeeded().catch(()=>{})
await page.waitForTimeout(500)
await page.screenshot({ path: `${OUT}/18-nav.png` })
// 销售账号看到的系统入口
await page.evaluate(() => localStorage.removeItem("erp.token"))
await page.goto("http://localhost:3000/login")
await page.getByPlaceholder("请输入账号").fill("xiaoshou")
await page.getByPlaceholder("请输入密码").fill("123456")
await page.getByRole("button", { name: "登录" }).click()
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 30000 })
await page.waitForTimeout(2500)
const links2 = await page.locator("a[href^='/']").allTextContents()
console.log("sales nav:", links2.filter(Boolean).map(s=>s.trim()).join(" | "))
await browser.close()
