import { chromium } from "@playwright/test"
const OUT = "/private/tmp/claude-501/-Users-huangjiajiang-Development-erp/fda94318-8842-42d7-bbfe-c5956adaaa39/scratchpad"
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } })
const page = await ctx.newPage()
await page.goto("http://localhost:3000/login")
await page.getByPlaceholder("请输入账号").fill("admin")
await page.getByPlaceholder("请输入密码").fill("123456")
await page.getByRole("button", { name: "登录" }).click()
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 30000 })
await page.waitForTimeout(1200)
await page.goto("http://localhost:3000/system/roles/role-root/edit")
await page.waitForTimeout(5000)
await page.screenshot({ path: `${OUT}/19-role-root.png` })
console.log("19 ok")
await page.goto("http://localhost:3000/system/roles/new")
await page.waitForTimeout(4000)
// 搜索 + 复制
await page.getByRole("searchbox", { name: "搜索权限" }).fill("销售单")
await page.waitForTimeout(1200)
await page.screenshot({ path: `${OUT}/20-role-new-search.png` })
console.log("20 ok")
await browser.close()
