import { chromium } from "@playwright/test"
const OUT = "/private/tmp/claude-501/-Users-huangjiajiang-Development-erp/fda94318-8842-42d7-bbfe-c5956adaaa39/scratchpad"
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } })
const page = await ctx.newPage()
page.on("console", (m) => { if (m.type() === "error") console.log("ERR:", m.text().slice(0,160)) })
await page.goto("http://localhost:3000/login")
await page.getByPlaceholder("请输入账号").fill("admin")
await page.getByPlaceholder("请输入密码").fill("123456")
await page.getByRole("button", { name: "登录" }).click()
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 30000 })
await page.waitForTimeout(1500)
await page.goto("http://localhost:3000/system/roles/role-sales/edit")
await page.waitForTimeout(7000)
await page.screenshot({ path: `${OUT}/10-role-edit-new.png` })
console.log("bar:", await page.locator("text=/已选/").first().innerText().catch(()=>"nf"))
console.log("checked:", await page.locator('[data-state="checked"]').count())
await browser.close()
