import { chromium } from "@playwright/test"
const OUT = "/private/tmp/claude-501/-Users-huangjiajiang-Development-erp/fda94318-8842-42d7-bbfe-c5956adaaa39/scratchpad"
const browser = await chromium.launch({ headless: true })
const ctx = await browser.newContext({ viewport: { width: 1600, height: 1000 } })
const page = await ctx.newPage()
page.on("pageerror", (e) => console.log("PAGEERROR:", e.message.slice(0,200)))
await page.goto("http://localhost:3000/login")
await page.getByPlaceholder("请输入账号").fill("admin")
await page.getByPlaceholder("请输入密码").fill("123456")
await page.getByRole("button", { name: "登录" }).click()
await page.waitForURL((u) => !u.pathname.includes("/login"), { timeout: 30000 })
await page.waitForTimeout(1500)
await page.goto("http://localhost:3000/system/access-audit?view=roles&subjectType=ROLE&subjectId=role-sales")
await page.waitForTimeout(5000)
await page.screenshot({ path: `${OUT}/16-explain-grouped.png` })
console.log("16 ok")
// 审计筛选面板
await page.goto("http://localhost:3000/system/audit")
await page.waitForTimeout(4000)
await page.getByRole("button", { name: /更多筛选/ }).click()
await page.waitForTimeout(1200)
await page.screenshot({ path: `${OUT}/17-audit-filters.png` })
console.log("17 ok")
await browser.close()
