apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: erp
    app.kubernetes.io/part-of: erp
  annotations:
    ingress.cloud.tencent.com/enable-group: "true"
    kubernetes.io/ingress.existLbId: {{ .Values.ingress.clbId | quote }}
    kubernetes.io/ingress.class: qcloud
    ingress.cloud.tencent.com/auto-rewrite: "true"
    ingress.cloud.tencent.com/tke-service-config: erp
spec:
  ingressClassName: qcloud
  tls:
    - hosts:
        - {{ .Values.ingress.webHost | quote }}
        - {{ .Values.ingress.apiHost | quote }}
      secretName: {{ .Values.ingress.tlsSecret | quote }}
  rules:
    - host: {{ .Values.ingress.webHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-client
                port:
                  number: 3000
    - host: {{ .Values.ingress.apiHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: erp-api
                port:
                  number: 10001
---
apiVersion: cloud.tencent.com/v1alpha1
kind: TkeServiceConfig
metadata:
  name: erp
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: erp
    app.kubernetes.io/part-of: erp
spec:
  loadBalancer:
    l7Listeners:
      - protocol: HTTPS
        port: 443
        domains:
          - domain: {{ .Values.ingress.apiHost | quote }}
            rules:
              - url: /
                forwardType: HTTP
                healthCheck:
                  enable: true
                  intervalTime: 10
                  timeout: 5
                  healthNum: 3
                  unHealthNum: 3
                  httpCheckPath: /health
                  httpCheckMethod: GET
                  httpCheckDomain: {{ .Values.ingress.apiHost | quote }}
                  httpCode: 2
