//! 域 D10 `catalog` 管理端路由。
//!
//! 经 `admin.rs` 的 `/admin` nest 后，最终路径为 `/admin/product-categories`、
//! `/admin/product-brands`、`/admin/unit-of-measures`、`/admin/sku-attributes`、
//! `/admin/sku-attribute-values`、`/admin/products`、`/admin/product-revisions`、
//! `/admin/skus`、`/admin/sku-revisions`、`/admin/voucher-category-profiles`（只读列表）、
//! `/admin/voucher-categories`（原子创建）、`/admin/voucher-categories/{sku_id}`（更新）；
//! 每条路由统一走 JWT + RBAC（`with_permission`），handler 标注
//! `#[permission_macros::permission]`。

use axum::{
    routing::{delete, get, post, put},
    Router,
};
use services::iam::SharedRbacService;

use crate::{
    app_state::AppState,
    core::{handler::catalog, middleware::with_permission},
};

/// 返回本域管理端路由集合。
///
/// # 参数
/// * `rbac` - 共享 Casbin RBAC 服务
///
/// # 返回
/// 返回挂载了权限校验层的路由集合。
pub fn routes(rbac: &SharedRbacService) -> Router<AppState> {
    Router::new()
        .route(
            "/product-categories",
            with_permission(
                get(catalog::product_category_list),
                rbac,
                catalog::product_category_list_permission_key(),
            ),
        )
        .route(
            "/product-categories",
            with_permission(
                post(catalog::product_category_create),
                rbac,
                catalog::product_category_create_permission_key(),
            ),
        )
        .route(
            "/product-categories/{id}",
            with_permission(
                put(catalog::product_category_update),
                rbac,
                catalog::product_category_update_permission_key(),
            ),
        )
        .route(
            "/product-categories/{id}/parent",
            with_permission(
                put(catalog::product_category_move),
                rbac,
                catalog::product_category_move_permission_key(),
            ),
        )
        .route(
            "/product-categories/{id}",
            with_permission(
                delete(catalog::product_category_delete),
                rbac,
                catalog::product_category_delete_permission_key(),
            ),
        )
        .route(
            "/product-brands",
            with_permission(
                get(catalog::product_brand_list),
                rbac,
                catalog::product_brand_list_permission_key(),
            ),
        )
        .route(
            "/product-brands",
            with_permission(
                post(catalog::product_brand_create),
                rbac,
                catalog::product_brand_create_permission_key(),
            ),
        )
        .route(
            "/product-brands/{id}",
            with_permission(
                put(catalog::product_brand_update),
                rbac,
                catalog::product_brand_update_permission_key(),
            ),
        )
        .route(
            "/product-brands/{id}",
            with_permission(
                delete(catalog::product_brand_delete),
                rbac,
                catalog::product_brand_delete_permission_key(),
            ),
        )
        .route(
            "/unit-of-measures",
            with_permission(
                get(catalog::unit_of_measure_list),
                rbac,
                catalog::unit_of_measure_list_permission_key(),
            ),
        )
        .route(
            "/unit-of-measures",
            with_permission(
                post(catalog::unit_of_measure_create),
                rbac,
                catalog::unit_of_measure_create_permission_key(),
            ),
        )
        .route(
            "/unit-of-measures/{id}",
            with_permission(
                put(catalog::unit_of_measure_update),
                rbac,
                catalog::unit_of_measure_update_permission_key(),
            ),
        )
        .route(
            "/unit-of-measures/{id}",
            with_permission(
                delete(catalog::unit_of_measure_delete),
                rbac,
                catalog::unit_of_measure_delete_permission_key(),
            ),
        )
        .route(
            "/sku-attributes",
            with_permission(
                get(catalog::sku_attribute_list),
                rbac,
                catalog::sku_attribute_list_permission_key(),
            ),
        )
        .route(
            "/sku-attributes",
            with_permission(
                post(catalog::sku_attribute_create),
                rbac,
                catalog::sku_attribute_create_permission_key(),
            ),
        )
        .route(
            "/sku-attributes/{id}",
            with_permission(
                put(catalog::sku_attribute_update),
                rbac,
                catalog::sku_attribute_update_permission_key(),
            ),
        )
        .route(
            "/sku-attributes/{id}",
            with_permission(
                delete(catalog::sku_attribute_delete),
                rbac,
                catalog::sku_attribute_delete_permission_key(),
            ),
        )
        .route(
            "/sku-attribute-values",
            with_permission(
                get(catalog::sku_attribute_value_list),
                rbac,
                catalog::sku_attribute_value_list_permission_key(),
            ),
        )
        .route(
            "/sku-attribute-values",
            with_permission(
                post(catalog::sku_attribute_value_create),
                rbac,
                catalog::sku_attribute_value_create_permission_key(),
            ),
        )
        .route(
            "/sku-attribute-values/{id}",
            with_permission(
                put(catalog::sku_attribute_value_update),
                rbac,
                catalog::sku_attribute_value_update_permission_key(),
            ),
        )
        .route(
            "/sku-attribute-values/{id}",
            with_permission(
                delete(catalog::sku_attribute_value_delete),
                rbac,
                catalog::sku_attribute_value_delete_permission_key(),
            ),
        )
        .route(
            "/products",
            with_permission(
                get(catalog::product::product_list),
                rbac,
                catalog::product::product_list_permission_key(),
            ),
        )
        .route(
            "/products",
            with_permission(
                post(catalog::product::product_create),
                rbac,
                catalog::product::product_create_permission_key(),
            ),
        )
        .route(
            "/products/{id}",
            with_permission(
                put(catalog::product::product_update),
                rbac,
                catalog::product::product_update_permission_key(),
            ),
        )
        .route(
            "/products/{id}/listing-status",
            with_permission(
                put(catalog::product::product_listing_update),
                rbac,
                catalog::product::product_listing_update_permission_key(),
            ),
        )
        .route(
            "/product-revisions",
            with_permission(
                get(catalog::product::product_revision_list),
                rbac,
                catalog::product::product_revision_list_permission_key(),
            ),
        )
        .route(
            "/skus",
            with_permission(
                get(catalog::product::sku_list),
                rbac,
                catalog::product::sku_list_permission_key(),
            ),
        )
        .route(
            "/skus/{id}/listing-status",
            with_permission(
                put(catalog::product::sku_listing_update),
                rbac,
                catalog::product::sku_listing_update_permission_key(),
            ),
        )
        .route(
            "/sellable-skus",
            with_permission(
                get(catalog::product::sellable_sku_list),
                rbac,
                catalog::product::sellable_sku_list_permission_key(),
            ),
        )
        .route(
            "/sku-revisions",
            with_permission(
                get(catalog::product::sku_revision_list),
                rbac,
                catalog::product::sku_revision_list_permission_key(),
            ),
        )
        .route(
            "/voucher-category-profiles",
            with_permission(
                get(catalog::product::voucher_category_profile_list),
                rbac,
                catalog::product::voucher_category_profile_list_permission_key(),
            ),
        )
        .route(
            "/voucher-categories",
            with_permission(
                post(catalog::product::voucher_category_create),
                rbac,
                catalog::product::voucher_category_create_permission_key(),
            ),
        )
        .route(
            "/voucher-categories/{sku_id}",
            with_permission(
                put(catalog::product::voucher_category_update),
                rbac,
                catalog::product::voucher_category_update_permission_key(),
            ),
        )
}
