[package]
name = "erp-identity"
version = "0.1.0"
edition = "2021"
autotests = false

[dependencies]
application-core = { workspace = true }
argon2 = { workspace = true }
async-trait = { workspace = true }
casbin = { workspace = true }
chrono = { workspace = true }
entity-core = { workspace = true }
entity-macros = { workspace = true }
erp-core = { workspace = true }
futures-util = { workspace = true }
id-generator = { workspace = true }
md5 = { workspace = true }
mongodb = { workspace = true }
persistence-core = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "macros"] }
tracing = { workspace = true }
validator = { workspace = true }
