[package]
name = "erp-processes"
version = "0.1.0"
edition = "2021"
autotests = false

[dependencies]
futures-util = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
erp-sales = { workspace = true }
erp-procurement = { workspace = true }
erp-fulfillment = { workspace = true }
erp-returns = { workspace = true }
erp-integration = { workspace = true }
erp-supply = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
erp-read-models = { workspace = true }
erp-finance = { workspace = true }
application-core = { workspace = true }
async-trait = { workspace = true }
bpm = { workspace = true }
entity-core = { workspace = true }
erp-audit = { workspace = true }
erp-core = { workspace = true }
erp-identity = { workspace = true }
erp-workflow = { workspace = true }
erp-support = { workspace = true }
erp-party = { workspace = true }
erp-customer = { workspace = true }
erp-supplier = { workspace = true }
erp-catalog = { workspace = true }
erp-warehouse = { workspace = true }
erp-contract = { workspace = true }
erp-import = { workspace = true }
erp-inventory = { workspace = true }
id-generator = { workspace = true }
mongodb = { workspace = true }
persistence-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
storage = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tracing = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
test-support = { workspace = true }
