/// 财务推荐权限。
pub(crate) const FINANCE_PERMISSIONS: &[&str] = &[
    "warehouse:list",
    "business_person:list",
    "settlement_party:list",
    "sales_invoice_request:list",
    "sales_invoice_request:detail",
    "sales_invoice_request:submit",
    "sales_invoice_request:cancel",
    "finance_responsibility:list",
    "finance_responsibility:manage",
    "work_item:list",
    "work_item:detail",
    "approval_instance:read",
    "approval_instance:decide",
    "approval_instance:cancel",
    "integration_task:process",
    "integration_task:complete",
    "legacy_import_confirmation:list",
    "legacy_import_confirmation:detail",
    "legacy_import_confirmation:complete",
    "file_asset:list",
    "file_asset:create",
    "file_asset:detail",
    "file_asset:update",
    "document_attachment:list",
    "document_attachment:create",
    "business_document:list",
    "business_document:detail",
    "document_relation:list",
    "document_participant:list",
    // 上下文只读（往来主体搜索：登记回款/销项发票需选择结算主体）
    "party:list",
    "party:detail",
    "party_revision:list",
    "sales_person:list",
    "procurement_person:list",
    "customer:list",
    "customer:detail",
    "customer_scope:detail",
    "customer_sensitive:reveal",
    "party_bank_account:list",
    "party_bank_account:detail",
    "party_bank_account:create",
    "party_bank_account:update",
    "party_bank_account:reveal",
    "supplier:list",
    "supplier:detail",
    "sales_order:list",
    "sales_order:detail",
    "sales_change_order:list",
    "sales_change_order:detail",
    "purchase_order:list",
    "purchase_order:detail",
    // 采购变更复核：审批区与变更清单需要读取变更单（决定走 approval_instance:decide）
    "purchase_change_order:list",
    "purchase_change_order:detail",
    // 库存调整复核：审批区与调整单详情需要读取调整单（决定走 approval_instance:decide）
    "stock_adjustment:list",
    "stock_adjustment:detail",
    "contract:list",
    "contract:detail",
    // 客户往来
    "receivable_account:*",
    "customer_receipt:*",
    "invoice:*",
    // 供应商往来
    "payable_account:*",
    "supplier_payment:*",
    "purchase_invoice_allocation:*",
    // 成本与结算
    "cost_entry:*",
    "cost_allocation:list",
    "supplier_settlement_statement:*",
    "supplier_settlement_item:list",
    "supplier_settlement_difference:*",
    // 退货退款冲正
    "sales_return_case:*",
    "purchase_return_order:*",
    "customer_refund:*",
    "supplier_refund:*",
    "receipt_reversal:*",
    "payment_reversal:*",
    "supplier_offering:list",
    "product:detail",
    "background_job:*",
    "background_job_item:list",
];
