/// 采购推荐权限。
pub(crate) const PROCUREMENT_PERMISSIONS: &[&str] = &[
    "business_person:list",
    "settlement_party:list",
    "company:list",
    "company:detail",
    "procurement_responsibility:list",
    "work_item:list",
    "work_item:detail",
    "approval_instance:read",
    "approval_instance:decide",
    "approval_instance:cancel",
    "integration_task:process",
    "integration_task:complete",
    // W29 责任任务对象读取；不授 list，治理菜单仍只对系统管理员开放。
    "integration_error_task:detail",
    "reconciliation_difference:detail",
    "legacy_import_confirmation:list",
    "legacy_import_confirmation:detail",
    "legacy_import_confirmation:complete",
    // W18 确认任务的业务对象读取权；不授 batch:list，避免打开导入治理菜单。
    "legacy_import_batch:detail",
    "file_asset:list",
    "file_asset:create",
    "file_asset:detail",
    "file_asset:preview",
    "file_asset:update",
    "document_attachment:list",
    "document_attachment:create",
    "business_document:list",
    "business_document:detail",
    "document_relation:list",
    "document_participant:list",
    // 商品主数据
    "product_category:*",
    "product_brand:*",
    "unit_of_measure:*",
    "sku_attribute:*",
    "sku_attribute_value:*",
    "product:*",
    "product_revision:list",
    "sku:list",
    "sku_revision:list",
    "sellable_sku:list",
    "voucher_category_profile:list",
    "warehouse:list",
    "warehouse:create",
    "warehouse:update",
    "warehouse_revision:list",
    "warehouse_sku_policy:*",
    // 供应商
    "party:list",
    "party:detail",
    "party:create",
    "party:update",
    "party_revision:list",
    "party_contact:*",
    "party_address:*",
    "party_tax_profile:*",
    "party_bank_account:*",
    "supplier:*",
    "supplier_sensitive:reveal",
    // 确认与采购
    "contract:detail",
    "sales_order:list",
    "sales_order:detail",
    "procurement_person:list",
    "purchase_order:*",
    "purchase_change_order:*",
    // 销售变更履约影响确认（财务复核仍由 work_item 责任角色隔离）
    "sales_change_order:list",
    "sales_change_order:detail",
    "sales_change_order:approve",
    "sales_change_order:reject",
    // 采购退货（财务保留票款冲正，不替代采购建单）
    "purchase_return_order:list",
    "purchase_return_order:create",
    "purchase_return_order:detail",
    // 履约作业
    "purchase_receipt:*",
    "delivery:*",
    "electronic_delivery:*",
    "service_fulfillment:*",
    // 库存只读：核验入库结果、预占与变更影响
    "stock_balance:list",
    "stock_balance:detail",
    "stock_movement:list",
    "stock_reservation:list",
    // 供应商供给 / API / 订单
    "supplier_offering:*",
    "supplier_offering_availability:*",
    "supplier_offering_cost:detail",
    "supplier_api_connection:list",
    "supplier_api_connection:create",
    "supplier_api_connection:detail",
    "supplier_api_connection:update",
    "supplier_api_connection:update_business_profile",
    "supplier_api_capability:list",
    "supplier_api_capability:confirm_requirement",
    "supplier_fulfillment_order:*",
    "supplier_refund_fact:post",
    // 应付只读
    "payable_account:list",
    "payable_account:detail",
    "supplier_payment:list",
    "supplier_payment:detail",
    // 供应商结算协同：查看与补证；正式结论由结算经办人在服务层二次校验
    "supplier_settlement_statement:list",
    "supplier_settlement_statement:detail",
    "supplier_settlement_item:list",
    "supplier_settlement_difference:list",
    "supplier_settlement_difference:update",
    "background_job:*",
    "background_job_item:list",
];
