/// 销售领导推荐权限。
pub(crate) const SALES_LEADER_PERMISSIONS: &[&str] = &[
    "sales_invoice_request:list",
    "sales_invoice_request:detail",
    "sales_invoice_request:submit",
    "sales_invoice_request:cancel",
    "work_item:list",
    "work_item:detail",
    // 直接指派的审批任务依赖 manage 参与权可见（与采购/财务等审批角色一致）；
    // 无 manage 时既非创建人又非参与人，任务会被参与权过滤掉。
    "work_item:manage",
    "approval_instance:read",
    "approval_instance:decide",
    "approval_instance:cancel",
    "file_asset:list",
    "file_asset:detail",
    "document_attachment:list",
    "business_document:list",
    "business_document:detail",
    "customer:list",
    "customer:detail",
    "customer_scope:detail",
    "contract:list",
    "contract:detail",
    "sales_order:list",
    "sales_order:detail",
    "sales_change_order:list",
    "sales_change_order:detail",
    "sales_change_order:approve",
    "sales_change_order:reject",
    "receivable_account:list",
    "receivable_account:detail",
    "customer_receipt:list",
    "customer_receipt:detail",
    "invoice:list",
    "invoice:detail",
    "cost_entry:list",
    "cost_entry:detail",
    "cost_allocation:list",
    "product:detail",
    "background_job:*",
    "background_job_item:list",
];
