[package]
name = "database"
version = "0.1.0"
edition = "2021"
autotests = false

[dependencies]
mongodb = { workspace = true }
casbin = { workspace = true }
async-trait = { workspace = true }
futures-util = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
bpm = { workspace = true }
entity-core = { workspace = true }
erp-core = { workspace = true }
persistence-core = { workspace = true }
erp-identity = { workspace = true }
erp-audit = { workspace = true }
erp-workflow = { workspace = true }
erp-support = { workspace = true }
erp-party = { workspace = true }
erp-customer = { workspace = true }
erp-supplier = { workspace = true }
erp-catalog = { workspace = true }
erp-warehouse = { workspace = true }
erp-contract = { workspace = true }
entities = { workspace = true }
application-core = { workspace = true }
regex = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
test-support = { workspace = true }
