[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
config = { workspace = true }
database = { workspace = true }
rpassword = "7.4.0"
services = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
