[package]
name = "cli"
version = "0.1.0"
edition = "2021"
autotests = false

[dependencies]
clap = { workspace = true }
config = { workspace = true }
erp-identity = { workspace = true }
erp-audit = { workspace = true }
persistence-core = { workspace = true }
rpassword = "7.4.0"
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

erp-workflow = { workspace = true }

erp-support = { workspace = true }

erp-catalog = { workspace = true }

erp-contract = { workspace = true }

erp-finance = { workspace = true }

erp-customer = { workspace = true }

erp-fulfillment = { workspace = true }

erp-integration = { workspace = true }

erp-inventory = { workspace = true }

erp-import = { workspace = true }

erp-party = { workspace = true }

erp-procurement = { workspace = true }

erp-returns = { workspace = true }

erp-sales = { workspace = true }

erp-supplier = { workspace = true }

erp-supply = { workspace = true }

erp-warehouse = { workspace = true }

erp-processes = { workspace = true }

mongodb = { workspace = true }
