//! Proposal lifecycle steps execute under the process-owned transaction.

use async_trait::async_trait;
use erp_core::common::time::Instant;
use mongodb::Database;
use persistence_core::{Executor, PageResult};
use serde_json::Value;

use super::{
    CatalogDraftEffectiveCommand, CatalogDraftFilter, CatalogPortalExt, NewProductDraft, NewProductInput,
    NormalizedProduct, PackagingInput,
};
use crate::{CatalogService, Error, Result};

/// Catalog delegates all opaque supply commercial terms to their owning domain.
#[async_trait]
pub trait PortalSupplyTermsPort: Send + Sync {
    /// Validate a submitted commercial snapshot without copying supply rules.
    /// # 参数
    /// `snapshot` 是供应商原始报价，`executor` 是当前事务。
    /// # 返回
    /// 条款合法时成功。
    /// # 错误
    /// 非法金额、税率、数量或供货规则返回错误。
    async fn validate(&self, snapshot: &Value, executor: &mut dyn Executor) -> Result<()>;

    /// Validate the original package price through the supply domain.
    /// # 参数
    /// `packaging` 为供应商确认保留的原始包装报价，`executor` 为当前事务。
    /// # 返回
    /// 原价符合供给金额规则时成功，不自动计算基础单位价格。
    /// # 错误
    /// 非法原价或供给规则失败。
    async fn validate_packaging(&self, packaging: &PackagingInput, executor: &mut dyn Executor)
    -> Result<()>;
}

/// Catalog-owned proposal lifecycle and formal materialization steps.
pub struct CatalogPortalService {
    pub(super) db: Database,
    pub(super) catalog: CatalogService,
}

/// Concrete submission identity generated by the process, separate from supplier input.
pub struct CatalogDraftSubmitCommand {
    pub expected_version: u64,
    pub submission_id: String,
    pub task_id: String,
    pub actor_id: String,
}

impl CatalogPortalService {
    /// Bind the same catalog authorization source used by internal maintenance.
    /// # 参数
    /// `db` 是目标数据库，`catalog` 必须注入商品范围授权。
    /// # 返回
    /// 不缓存授权的提报服务。
    /// # 错误
    /// 无。
    pub fn new(db: Database, catalog: CatalogService) -> Self {
        Self { db, catalog }
    }

    /// Save an incomplete proposal without creating formal master data.
    /// # 参数
    /// `id` 为预生成身份，其余参数为服务端供应商、真实操作人、草稿和事务。
    /// # 返回
    /// 已保存草稿。
    /// # 错误
    /// 输入非法、身份重复或数据库错误。
    pub async fn create(
        &self,
        id: String,
        supplier_id: String,
        actor_id: String,
        input: NewProductInput,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let draft = NewProductDraft::new(id, supplier_id, actor_id, input)?;
        self.db.new_product_drafts().create(&draft, executor).await?;
        Ok(draft)
    }

    /// Update only the authenticated supplier's editable draft.
    /// # 参数
    /// `id`、`supplier_id`、`version` 为对象边界和版本；`input` 为新草稿。
    /// # 返回
    /// 新草稿及持久化版本。
    /// # 错误
    /// 不可见、已冻结、版本冲突或非法输入。
    pub async fn update(
        &self,
        id: &str,
        supplier_id: &str,
        version: u64,
        input: NewProductInput,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let mut draft = self.detail(id, supplier_id, executor).await?;
        draft.update(version, input)?;
        self.db.new_product_drafts().update(&mut draft, executor).await?;
        Ok(draft)
    }

    /// Freeze a complete submission and bind its concrete internal review task.
    /// # 参数
    /// `draft` 必须已由当前供应商读取；标识、版本、提交人及Port由Process提供。
    /// # 返回
    /// 已冻结待确认申请。
    /// # 错误
    /// 未填写必要原始值、条款非法、版本冲突或数据库错误。
    pub async fn submit(
        &self,
        mut draft: NewProductDraft,
        command: CatalogDraftSubmitCommand,
        terms: &dyn PortalSupplyTermsPort,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        self.validate_for_submission(&draft.draft, terms, executor).await?;
        draft.submit(
            command.expected_version,
            command.submission_id,
            command.task_id,
            command.actor_id,
            Instant::now(),
        )?;
        self.db.new_product_drafts().update(&mut draft, executor).await?;
        Ok(draft)
    }

    /// 批量写入前只读核对本组输入，并在正式提交事务中复用同一规则。
    /// # 参数
    /// `input` 为当前商品组原稿，`terms` 为供给域校验Port，`executor` 为调用方执行器。
    /// # 返回
    /// 资料、已选字典和原始包装报价均合法时返回空结果。
    /// # 错误
    /// 任一原始资料、商务规则、字典资格或版本失效时拒绝。
    pub async fn validate_for_submission(
        &self,
        input: &NewProductInput,
        terms: &dyn PortalSupplyTermsPort,
        executor: &mut dyn Executor,
    ) -> Result<()> {
        input.validate_submission()?;
        self.ensure_selected_dictionaries(input, executor).await?;
        for sku in &input.skus {
            terms.validate(&sku.supply_terms, executor).await?;
            if let Some(packaging) = &sku.packaging {
                terms.validate_packaging(packaging, executor).await?;
            }
        }
        Ok(())
    }

    /// Withdraw a supplier's pending submission while preserving its history.
    /// # 参数
    /// 标识、供应商、版本、真实操作人及调用方事务。
    /// # 返回
    /// 已撤回申请。
    /// # 错误
    /// 越界、已生效、版本冲突或数据库错误。
    pub async fn withdraw(
        &self,
        id: &str,
        supplier_id: &str,
        version: u64,
        actor_id: &str,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let mut draft = self.detail(id, supplier_id, executor).await?;
        let submission = current_submission_id(&draft)?;
        draft.withdraw(version, &submission, actor_id, Instant::now())?;
        self.db.new_product_drafts().update(&mut draft, executor).await?;
        Ok(draft)
    }

    /// Record a supplier-visible return decision in the original review transaction.
    /// # 参数
    /// 对象、版本、退回原因、内部真实操作人及事务。
    /// # 返回
    /// 已退回申请。
    /// # 错误
    /// 空原因、非法状态、版本冲突或数据库错误。
    pub async fn return_to_supplier(
        &self,
        id: &str,
        version: u64,
        reason: &str,
        actor_id: &str,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let mut draft = self.load(id, executor).await?;
        let submission = current_submission_id(&draft)?;
        draft.return_to_supplier(version, &submission, reason.to_string(), actor_id, Instant::now())?;
        self.db.new_product_drafts().update(&mut draft, executor).await?;
        Ok(draft)
    }

    /// Store a final result only after formal catalog, supply and task writes succeed.
    /// # 参数
    /// `command` 含对象版本、内部映射、全部正式结果、内部操作人及真实核对说明。
    /// # 返回
    /// 已生效申请。
    /// # 错误
    /// 缺核对说明、行结果缺失、状态或版本冲突、数据库错误。
    pub async fn mark_effective(
        &self,
        command: CatalogDraftEffectiveCommand,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let mut draft = self.load(&command.draft_id, executor).await?;
        let submission = current_submission_id(&draft)?;
        draft.mark_effective(&submission, command, Instant::now())?;
        self.record_category_mapping(&draft, executor).await?;
        self.db.new_product_drafts().update(&mut draft, executor).await?;
        Ok(draft)
    }

    /// Save a separate internal mapping while preserving the frozen supplier input.
    /// # 参数
    /// 精确对象版本、内部规范化映射及当前审核事务。
    /// # 返回
    /// 已保存映射的待确认申请。
    /// # 错误
    /// 实质改写、映射非法、版本冲突或数据库错误。
    pub async fn map(
        &self,
        id: &str,
        version: u64,
        normalized: NormalizedProduct,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let mut draft = self.load(id, executor).await?;
        self.ensure_dictionaries(draft.submitted()?, &normalized, executor).await?;
        draft.map(version, normalized)?;
        self.db.new_product_drafts().update(&mut draft, executor).await?;
        Ok(draft)
    }

    /// Read a proposal through the authenticated supplier boundary.
    /// # 参数
    /// `supplier_id` 只能取自已校验会话。
    /// # 返回
    /// 该供应商的申请。
    /// # 错误
    /// 未知和范围外对象统一返回不存在。
    pub async fn detail(
        &self,
        id: &str,
        supplier_id: &str,
        executor: &mut dyn Executor,
    ) -> Result<NewProductDraft> {
        let draft = self.load(id, executor).await?;
        if draft.supplier_id != supplier_id {
            return Err(Error::NotFound("新品申请不存在".into()));
        }
        Ok(draft)
    }

    /// Read an internal review subject; the Process must validate task and permission.
    /// # 参数
    /// `id` 为精确申请标识，`executor` 为当前事务。
    /// # 返回
    /// 原始申请及历史。
    /// # 错误
    /// 未知对象或数据库错误。
    pub async fn load(&self, id: &str, executor: &mut dyn Executor) -> Result<NewProductDraft> {
        self.db
            .new_product_drafts()
            .find_by_id(id, executor)
            .await?
            .ok_or_else(|| Error::NotFound("新品申请不存在".into()))
    }

    /// List only the supplier selected by the authenticated server context.
    /// # 参数
    /// `filter` 必须使用服务端供应商，分页上限100。
    /// # 返回
    /// 有界提报页。
    /// # 错误
    /// 分页非法或数据库错误。
    pub async fn list(
        &self,
        filter: &CatalogDraftFilter,
        executor: &mut dyn Executor,
    ) -> Result<PageResult<NewProductDraft>> {
        if filter.supplier_id.is_empty() || filter.page == 0 || !(1..=100).contains(&filter.page_size) {
            return Err(Error::ValidationError("供应商或分页参数非法".into()));
        }
        Ok(self.db.new_product_drafts().search(filter, executor).await?)
    }
}

fn current_submission_id(draft: &NewProductDraft) -> Result<String> {
    draft.current_submission_id.clone().ok_or_else(|| Error::BusinessLogicError("申请缺少当前提交".into()))
}
