/**
 * W14 seed fixtures — stable identity + immutable revisions.
 * Historical name snapshots must not follow later renames.
 */

import type {
  MasterDataCenterView,
  MasterDataListItem,
  MasterDataResource,
  PermissionDemoSnapshot,
} from "@/features/master-data/types"
import { MASTER_DATA_ROLE_DEFAULT } from "@/features/master-data/types"

/** 按演示角色解析默认落地资源；未知或缺失回落到采购默认。 */
export function resolveMasterDataRoleDefault(
  role?: string | null
): MasterDataResource {
  const resource = role ? MASTER_DATA_ROLE_DEFAULT[role] : undefined
  return resource ?? "sellable-items"
}

export const W14_PERMISSION_DEMO: PermissionDemoSnapshot = {
  hasModuleAccess: true,
  resourceAccess: {
    "sellable-items": true,
    products: true,
    "voucher-categories": true,
    suppliers: true,
    warehouses: true,
  },
  canExport: true,
  roleLabel: "采购",
  canRevealSensitive: true,
}

/** Warehouse write always fail-closed while Q1 unconfirmed. */
export const WAREHOUSE_WRITE_CODE = "WAREHOUSE_WRITE_OWNER_UNCONFIRMED"
export const WAREHOUSE_WRITE_MESSAGE =
  "Q1 未确认：仓库资料与 SKU 策略写责任未指定。查询可用，全部写操作暂不可用；仓储与系统管理员均不可维护。"

export const MOCK_SENSITIVE_REVEALS: Record<string, string> = {
  "reveal:sup_1:bank": "6222 **** **** 0188 · 开户名：鲜果直供供应链有限公司",
  "reveal:sup_2:bank": "6217 **** **** 5521 · 开户名：礼遇包装工坊",
  "reveal:wh_1:contact": "周航 · 138****6621 · 上海市浦东新区临港大道 88 号",
  "reveal:wh_2:contact": "陈璐 · 139****3102 · 广州市黄埔区保税物流园 B3",
}

function commonActions(
  resource: MasterDataResource,
  lifecycle: "ENABLED" | "DISABLED"
): {
  allowedActions: string[]
  actionBlockers: MasterDataListItem["actionBlockers"]
} {
  if (resource === "warehouses") {
    return {
      allowedActions: ["VIEW", "EXPORT_ROW"],
      actionBlockers: [
        {
          action: "CREATE",
          code: WAREHOUSE_WRITE_CODE,
          message: WAREHOUSE_WRITE_MESSAGE,
        },
        {
          action: "CREATE_REVISION",
          code: WAREHOUSE_WRITE_CODE,
          message: WAREHOUSE_WRITE_MESSAGE,
        },
        {
          action: "DISABLE",
          code: WAREHOUSE_WRITE_CODE,
          message: WAREHOUSE_WRITE_MESSAGE,
        },
        {
          action: "MAINTAIN_POLICY",
          code: WAREHOUSE_WRITE_CODE,
          message: WAREHOUSE_WRITE_MESSAGE,
        },
      ],
    }
  }

  const allowed: string[] = ["VIEW", "EXPORT_ROW"]
  const blockers: Array<{ action: string; code: string; message: string }> = []
  if (lifecycle === "ENABLED") {
    allowed.push("CREATE_REVISION", "DISABLE")
  } else {
    allowed.push("CREATE_REVISION")
    blockers.push({
      action: "DISABLE",
      code: "ALREADY_DISABLED",
      message: "对象已停用；停用不是删除，历史版本仍可只读打开。",
    })
  }
  return { allowedActions: allowed, actionBlockers: blockers }
}

export const MASTER_DATA_LIST_SEEDS: Record<
  MasterDataResource,
  MasterDataListItem[]
> = {
  "sellable-items": [
    {
      objectType: "sellable-items",
      stableId: "si_1",
      stableNo: "SI-2026-0188",
      name: "新春坚果礼盒 · 典藏款",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "si_1_r6",
      displayedRevisionId: "si_1_r6",
      revisionNo: 6,
      effectiveFrom: "2026-01-01",
      effectiveTo: "2026-12-31",
      keyFacts: [
        { label: "SKU", value: "SKU-NY-BOX-01" },
        { label: "参考供应商", value: "鲜果直供" },
        { label: "参考含税成本", value: "¥128.00" },
        { label: "服务区域", value: "华东" },
      ],
      selectorEligibility: [
        {
          context: "sales_pick",
          contextLabel: "销售选品",
          eligible: true,
          blockerCodes: [],
        },
        {
          context: "procurement",
          contextLabel: "采购确认",
          eligible: true,
          blockerCodes: [],
        },
      ],
      ...commonActions("sellable-items", "ENABLED"),
      lockVersion: 6,
      ownerName: "赵强",
      metricTags: ["enabled"],
    },
    {
      objectType: "sellable-items",
      stableId: "si_2",
      stableNo: "SI-2026-0201",
      name: "员工生日蛋糕卡",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      scheduledLifecycleStatus: "DISABLED",
      scheduledLifecycleLabel: "待生效后停用",
      revisionTiming: "FUTURE",
      revisionTimingLabel: "待生效",
      currentRevisionId: "si_2_r2",
      displayedRevisionId: "si_2_r3",
      revisionNo: 3,
      effectiveFrom: "2026-09-01",
      effectiveTo: "2026-12-31",
      keyFacts: [
        { label: "SKU", value: "SKU-CARD-BDAY" },
        { label: "参考供应商", value: "—" },
        { label: "服务区域", value: "全国" },
      ],
      primaryBlocker: undefined,
      selectorEligibility: [
        {
          context: "sales_pick",
          contextLabel: "销售选品",
          eligible: true,
          blockerCodes: [],
          reason: "当前版本仍可选；待生效停用未提前改启停",
        },
      ],
      ...commonActions("sellable-items", "ENABLED"),
      lockVersion: 3,
      ownerName: "李倩",
      metricTags: ["enabled", "pending", "expiring"],
    },
    {
      objectType: "sellable-items",
      stableId: "si_3",
      stableNo: "SI-2025-0902",
      name: "中秋月饼礼盒（旧版）",
      lifecycleStatus: "DISABLED",
      lifecycleStatusLabel: "当前停用",
      lifecycleTone: "neutral",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "si_3_r9",
      displayedRevisionId: "si_3_r9",
      revisionNo: 9,
      effectiveFrom: "2025-08-01",
      effectiveTo: "2025-10-31",
      keyFacts: [
        { label: "SKU", value: "SKU-MOON-09" },
        { label: "参考供应商", value: "礼遇包装" },
      ],
      primaryBlocker: "已停用：不可进入销售选品",
      selectorEligibility: [
        {
          context: "sales_pick",
          contextLabel: "销售选品",
          eligible: false,
          blockerCodes: ["LIFECYCLE_DISABLED"],
          reason: "当前停用",
        },
      ],
      ...commonActions("sellable-items", "DISABLED"),
      lockVersion: 9,
      ownerName: "赵强",
      metricTags: ["disabled"],
    },
  ],
  products: [
    {
      objectType: "products",
      stableId: "prd_1",
      stableNo: "SKU-NY-BOX-01",
      name: "新春坚果礼盒 · 典藏款",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "prd_1_r6",
      displayedRevisionId: "prd_1_r6",
      revisionNo: 6,
      effectiveFrom: "2026-01-01",
      keyFacts: [
        { label: "SPU", value: "SPU-NY-BOX" },
        { label: "基础单位", value: "套" },
        { label: "规格签名", value: "sig:ny-box-01@v1" },
      ],
      selectorEligibility: [
        {
          context: "sku_pick",
          contextLabel: "选择商品/SKU",
          eligible: true,
          blockerCodes: [],
        },
      ],
      ...commonActions("products", "ENABLED"),
      lockVersion: 6,
      metricTags: ["enabled"],
    },
    {
      objectType: "products",
      stableId: "prd_2",
      stableNo: "SKU-TEA-09",
      name: "礼盒红茶",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "prd_2_r3",
      displayedRevisionId: "prd_2_r3",
      revisionNo: 3,
      effectiveFrom: "2026-02-01",
      keyFacts: [
        { label: "SPU", value: "SPU-TEA" },
        { label: "基础单位", value: "盒" },
        { label: "规格签名", value: "sig:tea-09@v1" },
      ],
      primaryBlocker: "基础单位已被已生效单据引用，不可在同 SKU 修订中变更",
      selectorEligibility: [
        {
          context: "sku_pick",
          contextLabel: "选择商品/SKU",
          eligible: true,
          blockerCodes: [],
        },
      ],
      allowedActions: ["VIEW", "EXPORT_ROW", "CREATE_REVISION", "DISABLE"],
      actionBlockers: [
        {
          action: "CHANGE_BASE_UNIT",
          code: "BASE_UNIT_LOCKED",
          message:
            "SKU 已被已生效单据使用，不得修改基础单位。请「停用并新建 SKU」。",
        },
        {
          action: "CHANGE_SPEC_SIGNATURE",
          code: "SPEC_SIGNATURE_IMMUTABLE",
          message:
            "规格身份变化必须新建 SKU，不允许通过同一 SKU 修订改变 specification_signature。",
        },
      ],
      lockVersion: 3,
      metricTags: ["enabled"],
    },
    {
      objectType: "products",
      stableId: "prd_3",
      stableNo: "SKU-OLD-88",
      name: "已下市果篮",
      lifecycleStatus: "DISABLED",
      lifecycleStatusLabel: "当前停用",
      lifecycleTone: "neutral",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "prd_3_r12",
      displayedRevisionId: "prd_3_r12",
      revisionNo: 12,
      effectiveFrom: "2025-01-01",
      effectiveTo: "2025-12-31",
      keyFacts: [
        { label: "SPU", value: "SPU-FRUIT" },
        { label: "基础单位", value: "篮" },
      ],
      primaryBlocker: "已停用：历史引用保留",
      selectorEligibility: [
        {
          context: "sku_pick",
          contextLabel: "选择商品/SKU",
          eligible: false,
          blockerCodes: ["LIFECYCLE_DISABLED"],
          reason: "当前停用",
        },
      ],
      ...commonActions("products", "DISABLED"),
      lockVersion: 12,
      metricTags: ["disabled"],
    },
  ],
  "voucher-categories": [
    {
      objectType: "voucher-categories",
      stableId: "vc_1",
      stableNo: "VC-BIRTHDAY",
      name: "员工生日卡",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "vc_1_r4",
      displayedRevisionId: "vc_1_r4",
      revisionNo: 4,
      effectiveFrom: "2026-01-01",
      keyFacts: [
        { label: "卡券 SKU", value: "SKU-CARD-BDAY" },
        { label: "说明", value: "不含商城玩法" },
      ],
      selectorEligibility: [
        {
          context: "voucher_category",
          contextLabel: "选择卡券类目",
          eligible: true,
          blockerCodes: [],
        },
      ],
      ...commonActions("voucher-categories", "ENABLED"),
      lockVersion: 4,
      metricTags: ["enabled"],
    },
    {
      objectType: "voucher-categories",
      stableId: "vc_2",
      stableNo: "VC-FESTIVAL",
      name: "节日慰问卡",
      lifecycleStatus: "DISABLED",
      lifecycleStatusLabel: "当前停用",
      lifecycleTone: "neutral",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "vc_2_r2",
      displayedRevisionId: "vc_2_r2",
      revisionNo: 2,
      effectiveFrom: "2025-01-01",
      effectiveTo: "2025-12-31",
      keyFacts: [
        { label: "卡券 SKU", value: "SKU-CARD-FEST" },
        { label: "说明", value: "不含商城玩法" },
      ],
      primaryBlocker: "已停用",
      selectorEligibility: [
        {
          context: "voucher_category",
          contextLabel: "选择卡券类目",
          eligible: false,
          blockerCodes: ["LIFECYCLE_DISABLED"],
          reason: "当前停用",
        },
      ],
      ...commonActions("voucher-categories", "DISABLED"),
      lockVersion: 2,
      metricTags: ["disabled"],
    },
  ],
  suppliers: [
    {
      objectType: "suppliers",
      stableId: "sup_1",
      stableNo: "SUP-2026-014",
      name: "鲜果直供供应链",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "sup_1_r3",
      displayedRevisionId: "sup_1_r3",
      revisionNo: 3,
      effectiveFrom: "2026-01-01",
      keyFacts: [
        { label: "角色", value: "实物供应" },
        { label: "商务结算", value: "v3" },
        { label: "资质", value: "正常" },
        { label: "银行账号", value: "6222 **** **** 0188", sensitive: true },
      ],
      selectorEligibility: [
        {
          context: "procurement_supplier",
          contextLabel: "采购选供应商",
          eligible: true,
          blockerCodes: [],
        },
      ],
      ...commonActions("suppliers", "ENABLED"),
      lockVersion: 3,
      ownerName: "赵强",
      metricTags: ["enabled"],
    },
    {
      objectType: "suppliers",
      stableId: "sup_2",
      stableNo: "SUP-2025-088",
      name: "礼遇包装工坊",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "warning",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "sup_2_r5",
      displayedRevisionId: "sup_2_r5",
      revisionNo: 5,
      effectiveFrom: "2025-06-01",
      keyFacts: [
        { label: "角色", value: "包装服务" },
        { label: "商务结算", value: "v5" },
        { label: "资质", value: "将到期" },
        { label: "银行账号", value: "6217 **** **** 5521", sensitive: true },
      ],
      primaryBlocker: "资质将于 30 日内到期（系统最新数据）",
      selectorEligibility: [
        {
          context: "procurement_supplier",
          contextLabel: "采购选供应商",
          eligible: true,
          blockerCodes: [],
          reason: "能力匹配；资质临近到期，提交时按业务日期再校验",
        },
      ],
      ...commonActions("suppliers", "ENABLED"),
      lockVersion: 5,
      ownerName: "李倩",
      metricTags: ["enabled", "expiring"],
    },
    {
      objectType: "suppliers",
      stableId: "sup_3",
      stableNo: "SUP-2024-003",
      name: "旧版物流商（停用）",
      lifecycleStatus: "DISABLED",
      lifecycleStatusLabel: "当前停用",
      lifecycleTone: "neutral",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "sup_3_r1",
      displayedRevisionId: "sup_3_r1",
      revisionNo: 1,
      effectiveFrom: "2024-01-01",
      effectiveTo: "2025-12-31",
      keyFacts: [
        { label: "角色", value: "配送" },
        { label: "资质", value: "已失效" },
      ],
      primaryBlocker: "已停用 / 资质失效",
      selectorEligibility: [
        {
          context: "procurement_supplier",
          contextLabel: "采购选供应商",
          eligible: false,
          blockerCodes: ["LIFECYCLE_DISABLED", "QUALIFICATION_EXPIRED"],
          reason: "当前停用且资质已失效",
        },
      ],
      ...commonActions("suppliers", "DISABLED"),
      lockVersion: 1,
      metricTags: ["disabled"],
    },
  ],
  warehouses: [
    {
      objectType: "warehouses",
      stableId: "wh_1",
      stableNo: "WH-EAST-01",
      name: "华东一号仓",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "wh_1_r2",
      displayedRevisionId: "wh_1_r2",
      revisionNo: 2,
      effectiveFrom: "2025-01-01",
      keyFacts: [
        { label: "区域", value: "华东" },
        { label: "联系人", value: "周航 · 138****6621", sensitive: true },
        { label: "SKU 预警策略", value: "安全库存 · 默认（只读）" },
        { label: "库存摘要", value: "在库 1,280 · 预占 42" },
      ],
      primaryBlocker: "写操作暂不可用（本期）",
      selectorEligibility: [
        {
          context: "warehouse_pick",
          contextLabel: "仓储选择仓库",
          eligible: true,
          blockerCodes: [],
        },
      ],
      ...commonActions("warehouses", "ENABLED"),
      lockVersion: 2,
      metricTags: ["enabled", "pending"],
    },
    {
      objectType: "warehouses",
      stableId: "wh_2",
      stableNo: "WH-SOUTH-02",
      name: "华南中转仓",
      lifecycleStatus: "ENABLED",
      lifecycleStatusLabel: "当前启用",
      lifecycleTone: "success",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "wh_2_r1",
      displayedRevisionId: "wh_2_r1",
      revisionNo: 1,
      effectiveFrom: "2025-06-01",
      keyFacts: [
        { label: "区域", value: "华南" },
        { label: "联系人", value: "陈璐 · 139****3102", sensitive: true },
        { label: "SKU 预警策略", value: "低周转加强（只读）" },
        { label: "库存摘要", value: "在库 86 · 预占 0" },
      ],
      primaryBlocker: "写操作暂不可用（本期）",
      selectorEligibility: [
        {
          context: "warehouse_pick",
          contextLabel: "仓储选择仓库",
          eligible: true,
          blockerCodes: [],
        },
      ],
      ...commonActions("warehouses", "ENABLED"),
      lockVersion: 1,
      metricTags: ["enabled", "pending"],
    },
    {
      objectType: "warehouses",
      stableId: "wh_3",
      stableNo: "WH-OLD-99",
      name: "已封存临时仓",
      lifecycleStatus: "DISABLED",
      lifecycleStatusLabel: "当前停用",
      lifecycleTone: "neutral",
      revisionTiming: "CURRENT",
      revisionTimingLabel: "当前",
      currentRevisionId: "wh_3_r3",
      displayedRevisionId: "wh_3_r3",
      revisionNo: 3,
      effectiveFrom: "2024-01-01",
      effectiveTo: "2025-03-31",
      keyFacts: [
        { label: "区域", value: "华北" },
        { label: "SKU 预警策略", value: "已停用" },
        { label: "库存摘要", value: "在库 0 · 预占 0" },
      ],
      primaryBlocker: "已停用（身份保留）",
      selectorEligibility: [
        {
          context: "warehouse_pick",
          contextLabel: "仓储选择仓库",
          eligible: false,
          blockerCodes: ["LIFECYCLE_DISABLED"],
          reason: "当前停用",
        },
      ],
      ...commonActions("warehouses", "DISABLED"),
      lockVersion: 3,
      metricTags: ["disabled"],
    },
  ],
}

function buildTimeline(
  entries: Array<{
    id: string
    revisionNo: number
    timing: "CURRENT" | "FUTURE" | "HISTORICAL"
    name: string
    actor: string
    from: string
    to?: string
    reason: string
    isCurrent: boolean
    lifecycle: "ENABLED" | "DISABLED"
  }>
): MasterDataCenterView["revisionTimeline"] {
  return entries.map((e) => ({
    id: e.id,
    revisionNo: e.revisionNo,
    revisionTiming: e.timing,
    timingLabel:
      e.timing === "CURRENT"
        ? "当前"
        : e.timing === "FUTURE"
          ? "待生效"
          : "已结束",
    nameSnapshot: e.name,
    actor: e.actor,
    effectiveFrom: e.from,
    effectiveTo: e.to,
    changeReason: e.reason,
    isCurrent: e.isCurrent,
    lifecycleAtRevision: e.lifecycle,
  }))
}

export const MASTER_DATA_CENTER_SEEDS: Record<string, MasterDataCenterView> = {
  si_1: {
    resource: "sellable-items",
    stableId: "si_1",
    stableNo: "SI-2026-0188",
    name: "新春坚果礼盒 · 典藏款",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 6,
    currentRevision: {
      revisionId: "si_1_r6",
      revisionNo: 6,
      name: "新春坚果礼盒 · 典藏款",
      effectiveFrom: "2026-01-01",
      effectiveTo: "2026-12-31",
      changeReason: "调整参考含税成本与交期",
      actor: "赵强",
      fields: [
        { label: "SKU", value: "SKU-NY-BOX-01" },
        { label: "参考供应商", value: "鲜果直供供应链" },
        { label: "参考含税成本", value: "¥128.00" },
        { label: "服务区域", value: "华东" },
        { label: "交期", value: "5 个工作日" },
        { label: "允许履约方式", value: "仓发 / 代发" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "si_1_r6",
        revisionNo: 6,
        timing: "CURRENT",
        name: "新春坚果礼盒 · 典藏款",
        actor: "赵强",
        from: "2026-01-01",
        to: "2026-12-31",
        reason: "调整参考含税成本与交期",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
      {
        id: "si_1_r5",
        revisionNo: 5,
        timing: "HISTORICAL",
        name: "新春坚果礼盒 · 经典款",
        actor: "赵强",
        from: "2025-11-01",
        to: "2025-12-31",
        reason: "更名典藏款前的历史记录",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
      {
        id: "si_1_r1",
        revisionNo: 1,
        timing: "HISTORICAL",
        name: "新春坚果礼盒",
        actor: "系统导入",
        from: "2025-01-01",
        to: "2025-10-31",
        reason: "首版创建",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "sales_pick",
        contextLabel: "销售选品",
        eligible: true,
        blockerCodes: [],
      },
      {
        context: "procurement",
        contextLabel: "采购确认",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 42,
      note: "历史销售单引用精确修订 ID；当前名称变更不回填历史记录。",
    },
    sensitiveFields: [],
    resourceFacts: [
      { label: "税率", value: "13%" },
      { label: "资质校验", value: "通过（eligibilityAsOf 服务端）" },
    ],
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [],
    auditEvents: [
      {
        id: "a1",
        at: "2026-01-01T09:12:00+08:00",
        actor: "赵强",
        action: "形成新版本",
        detail: "v6 · 调整参考成本",
      },
      {
        id: "a0",
        at: "2025-01-01T10:00:00+08:00",
        actor: "系统导入",
        action: "新建",
        detail: "v1 稳定身份 SI-2026-0188",
      },
    ],
    sections: ["overview", "versions", "relations", "audit"],
  },
  si_2: {
    resource: "sellable-items",
    stableId: "si_2",
    stableNo: "SI-2026-0201",
    name: "员工生日蛋糕卡",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    scheduledLifecycleStatus: "DISABLED",
    scheduledLifecycleLabel: "待生效后停用",
    revisionTiming: "FUTURE",
    revisionTimingLabel: "待生效",
    lockVersion: 3,
    currentRevision: {
      revisionId: "si_2_r2",
      revisionNo: 2,
      name: "员工生日蛋糕卡",
      effectiveFrom: "2026-03-01",
      effectiveTo: "2026-08-31",
      changeReason: "启用全国区域",
      actor: "李倩",
      fields: [
        { label: "SKU", value: "SKU-CARD-BDAY" },
        { label: "参考供应商", value: "二次确认时选择" },
        { label: "服务区域", value: "全国" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "si_2_r3",
        revisionNo: 3,
        timing: "FUTURE",
        name: "员工生日蛋糕卡",
        actor: "李倩",
        from: "2026-09-01",
        to: "2026-12-31",
        reason: "计划停用（待生效，不改当前启停）",
        isCurrent: false,
        lifecycle: "DISABLED",
      },
      {
        id: "si_2_r2",
        revisionNo: 2,
        timing: "CURRENT",
        name: "员工生日蛋糕卡",
        actor: "李倩",
        from: "2026-03-01",
        to: "2026-08-31",
        reason: "启用全国区域",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
      {
        id: "si_2_r1",
        revisionNo: 1,
        timing: "HISTORICAL",
        name: "生日蛋糕卡（试点）",
        actor: "李倩",
        from: "2025-12-01",
        to: "2026-02-28",
        reason: "试点上线",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "sales_pick",
        contextLabel: "销售选品",
        eligible: true,
        blockerCodes: [],
        reason: "当前版本可选；待生效停用不混入启停状态",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 11,
      note: "待生效修订不影响当前选择器结果，直至 effectiveFrom。",
    },
    sensitiveFields: [],
    resourceFacts: [
      { label: "允许履约方式", value: "电子卡券" },
      { label: "卡券类目", value: "VC-BIRTHDAY" },
    ],
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [],
    auditEvents: [
      {
        id: "a2",
        at: "2026-07-15T14:00:00+08:00",
        actor: "李倩",
        action: "形成待生效版本",
        detail: "v3 计划 2026-09-01 停用",
      },
    ],
    sections: ["overview", "versions", "relations", "audit"],
  },
  si_3: {
    resource: "sellable-items",
    stableId: "si_3",
    stableNo: "SI-2025-0902",
    name: "中秋月饼礼盒（旧版）",
    lifecycleStatus: "DISABLED",
    lifecycleStatusLabel: "当前停用",
    lifecycleTone: "neutral",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 9,
    currentRevision: {
      revisionId: "si_3_r9",
      revisionNo: 9,
      name: "中秋月饼礼盒（旧版）",
      effectiveFrom: "2025-08-01",
      effectiveTo: "2025-10-31",
      changeReason: "季节结束后停用",
      actor: "赵强",
      fields: [
        { label: "SKU", value: "SKU-MOON-09" },
        { label: "参考供应商", value: "礼遇包装工坊" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "si_3_r9",
        revisionNo: 9,
        timing: "CURRENT",
        name: "中秋月饼礼盒（旧版）",
        actor: "赵强",
        from: "2025-08-01",
        to: "2025-10-31",
        reason: "季节结束后停用",
        isCurrent: true,
        lifecycle: "DISABLED",
      },
      {
        id: "si_3_r8",
        revisionNo: 8,
        timing: "HISTORICAL",
        name: "中秋月饼礼盒 2025",
        actor: "赵强",
        from: "2025-07-01",
        to: "2025-07-31",
        reason: "赛季上架",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "sales_pick",
        contextLabel: "销售选品",
        eligible: false,
        blockerCodes: ["LIFECYCLE_DISABLED"],
        reason: "当前停用",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 28,
      note: "停用非删除：已引用身份保留，历史版本可只读打开。",
    },
    sensitiveFields: [],
    resourceFacts: [{ label: "停用说明", value: "季节性项目，身份永久保留" }],
    allowedActions: ["VIEW", "CREATE_REVISION"],
    actionBlockers: [
      {
        action: "DISABLE",
        code: "ALREADY_DISABLED",
        message: "对象已停用。",
      },
    ],
    auditEvents: [
      {
        id: "a3",
        at: "2025-10-31T18:00:00+08:00",
        actor: "赵强",
        action: "停用",
        detail: "v9 · 季节结束后停用",
      },
    ],
    sections: ["overview", "versions", "relations", "audit"],
  },
  prd_1: {
    resource: "products",
    stableId: "prd_1",
    stableNo: "SKU-NY-BOX-01",
    name: "新春坚果礼盒 · 典藏款",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 6,
    currentRevision: {
      revisionId: "prd_1_r6",
      revisionNo: 6,
      name: "新春坚果礼盒 · 典藏款",
      effectiveFrom: "2026-01-01",
      changeReason: "更新媒体与条码",
      actor: "赵强",
      fields: [
        { label: "SPU", value: "SPU-NY-BOX" },
        { label: "基础单位", value: "套" },
        { label: "规格签名", value: "sig:ny-box-01@v1" },
        { label: "分类", value: "礼盒" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "prd_1_r6",
        revisionNo: 6,
        timing: "CURRENT",
        name: "新春坚果礼盒 · 典藏款",
        actor: "赵强",
        from: "2026-01-01",
        reason: "更新媒体与条码",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
      {
        id: "prd_1_r5",
        revisionNo: 5,
        timing: "HISTORICAL",
        name: "新春坚果礼盒 · 经典款",
        actor: "赵强",
        from: "2025-10-01",
        to: "2025-12-31",
        reason: "历史名称记录",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "sku_pick",
        contextLabel: "选择商品/SKU",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 55,
      note: "规格签名不可变；变更须新建 SKU。",
    },
    sensitiveFields: [],
    resourceFacts: [
      { label: "规格签名", value: "sig:ny-box-01@v1" },
      { label: "基础单位", value: "套" },
    ],
    productConstraints: {
      specificationSignature: "sig:ny-box-01@v1",
      baseUnit: "套",
      hasFormalReferences: true,
    },
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [
      {
        action: "CHANGE_SPEC_SIGNATURE",
        code: "SPEC_SIGNATURE_IMMUTABLE",
        message: "规格身份变化必须新建 SKU。",
      },
      {
        action: "CHANGE_BASE_UNIT",
        code: "BASE_UNIT_LOCKED",
        message: "已被已生效单据使用，不得修改基础单位。",
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  prd_2: {
    resource: "products",
    stableId: "prd_2",
    stableNo: "SKU-TEA-09",
    name: "礼盒红茶",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 3,
    currentRevision: {
      revisionId: "prd_2_r3",
      revisionNo: 3,
      name: "礼盒红茶",
      effectiveFrom: "2026-02-01",
      changeReason: "更新分类标签",
      actor: "李倩",
      fields: [
        { label: "SPU", value: "SPU-TEA" },
        { label: "基础单位", value: "盒" },
        { label: "规格签名", value: "sig:tea-09@v1" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "prd_2_r3",
        revisionNo: 3,
        timing: "CURRENT",
        name: "礼盒红茶",
        actor: "李倩",
        from: "2026-02-01",
        reason: "更新分类标签",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
      {
        id: "prd_2_r1",
        revisionNo: 1,
        timing: "HISTORICAL",
        name: "红茶礼盒装",
        actor: "系统导入",
        from: "2025-01-01",
        to: "2026-01-31",
        reason: "首版",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "sku_pick",
        contextLabel: "选择商品/SKU",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 19,
      note: "演示：尝试改规格签名或基础单位将被阻断。",
    },
    sensitiveFields: [],
    resourceFacts: [
      { label: "规格签名", value: "sig:tea-09@v1" },
      { label: "基础单位", value: "盒（已锁定）" },
    ],
    productConstraints: {
      specificationSignature: "sig:tea-09@v1",
      baseUnit: "盒",
      hasFormalReferences: true,
    },
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [
      {
        action: "CHANGE_SPEC_SIGNATURE",
        code: "SPEC_SIGNATURE_IMMUTABLE",
        message:
          "规格身份变化必须新建 SKU，不允许通过同一 SKU 修订改变 specification_signature。",
      },
      {
        action: "CHANGE_BASE_UNIT",
        code: "BASE_UNIT_LOCKED",
        message:
          "SKU 已被已生效单据使用，不得修改基础单位。请「停用并新建 SKU」。",
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  prd_3: {
    resource: "products",
    stableId: "prd_3",
    stableNo: "SKU-OLD-88",
    name: "已下市果篮",
    lifecycleStatus: "DISABLED",
    lifecycleStatusLabel: "当前停用",
    lifecycleTone: "neutral",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 12,
    currentRevision: {
      revisionId: "prd_3_r12",
      revisionNo: 12,
      name: "已下市果篮",
      effectiveFrom: "2025-01-01",
      effectiveTo: "2025-12-31",
      changeReason: "下市停用",
      actor: "赵强",
      fields: [
        { label: "SPU", value: "SPU-FRUIT" },
        { label: "基础单位", value: "篮" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "prd_3_r12",
        revisionNo: 12,
        timing: "CURRENT",
        name: "已下市果篮",
        actor: "赵强",
        from: "2025-01-01",
        to: "2025-12-31",
        reason: "下市停用",
        isCurrent: true,
        lifecycle: "DISABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "sku_pick",
        contextLabel: "选择商品/SKU",
        eligible: false,
        blockerCodes: ["LIFECYCLE_DISABLED"],
        reason: "当前停用",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 7,
      note: "停用非删除，历史版本可只读。",
    },
    sensitiveFields: [],
    resourceFacts: [],
    productConstraints: {
      specificationSignature: "sig:old-88@v1",
      baseUnit: "篮",
      hasFormalReferences: true,
    },
    allowedActions: ["VIEW", "CREATE_REVISION"],
    actionBlockers: [
      {
        action: "DISABLE",
        code: "ALREADY_DISABLED",
        message: "对象已停用。",
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  vc_1: {
    resource: "voucher-categories",
    stableId: "vc_1",
    stableNo: "VC-BIRTHDAY",
    name: "员工生日卡",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 4,
    currentRevision: {
      revisionId: "vc_1_r4",
      revisionNo: 4,
      name: "员工生日卡",
      effectiveFrom: "2026-01-01",
      changeReason: "更新类目描述",
      actor: "运营-小陈",
      fields: [
        { label: "卡券 SKU", value: "SKU-CARD-BDAY" },
        { label: "product_kind", value: "VOUCHER" },
        { label: "ERP 类目描述", value: "员工生日慰问电子卡" },
        { label: "边界", value: "不含商城玩法 / 限购 / 员工端陈列" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "vc_1_r4",
        revisionNo: 4,
        timing: "CURRENT",
        name: "员工生日卡",
        actor: "运营-小陈",
        from: "2026-01-01",
        reason: "更新类目描述",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "voucher_category",
        contextLabel: "选择卡券类目",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 15,
      note: "只表达 ERP 销售项，不接收商城玩法字段。",
    },
    sensitiveFields: [],
    resourceFacts: [
      { label: "商城玩法", value: "不展示、不缓存、不保存" },
    ],
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  vc_2: {
    resource: "voucher-categories",
    stableId: "vc_2",
    stableNo: "VC-FESTIVAL",
    name: "节日慰问卡",
    lifecycleStatus: "DISABLED",
    lifecycleStatusLabel: "当前停用",
    lifecycleTone: "neutral",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 2,
    currentRevision: {
      revisionId: "vc_2_r2",
      revisionNo: 2,
      name: "节日慰问卡",
      effectiveFrom: "2025-01-01",
      effectiveTo: "2025-12-31",
      changeReason: "活动结束停用",
      actor: "运营-小陈",
      fields: [
        { label: "卡券 SKU", value: "SKU-CARD-FEST" },
        { label: "边界", value: "不含商城玩法" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "vc_2_r2",
        revisionNo: 2,
        timing: "CURRENT",
        name: "节日慰问卡",
        actor: "运营-小陈",
        from: "2025-01-01",
        to: "2025-12-31",
        reason: "活动结束停用",
        isCurrent: true,
        lifecycle: "DISABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "voucher_category",
        contextLabel: "选择卡券类目",
        eligible: false,
        blockerCodes: ["LIFECYCLE_DISABLED"],
        reason: "当前停用",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 4,
      note: "停用非删除。",
    },
    sensitiveFields: [],
    resourceFacts: [{ label: "商城玩法", value: "不展示" }],
    allowedActions: ["VIEW", "CREATE_REVISION"],
    actionBlockers: [
      {
        action: "DISABLE",
        code: "ALREADY_DISABLED",
        message: "对象已停用。",
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  sup_1: {
    resource: "suppliers",
    stableId: "sup_1",
    stableNo: "SUP-2026-014",
    name: "鲜果直供供应链",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 3,
    currentRevision: {
      revisionId: "sup_1_r3",
      revisionNo: 3,
      name: "鲜果直供供应链",
      effectiveFrom: "2026-01-01",
      changeReason: "更新商务结算版本",
      actor: "赵强",
      fields: [
        { label: "供应商角色", value: "实物供应" },
        { label: "商务结算版本", value: "v3" },
        { label: "能力版本", value: "生鲜冷链 · v2" },
        { label: "资质", value: "食品经营许可证 · 有效至 2027-06-30" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "sup_1_r3",
        revisionNo: 3,
        timing: "CURRENT",
        name: "鲜果直供供应链",
        actor: "赵强",
        from: "2026-01-01",
        reason: "更新商务结算版本",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
      {
        id: "sup_1_r2",
        revisionNo: 2,
        timing: "HISTORICAL",
        name: "鲜果直供（华东）",
        actor: "赵强",
        from: "2025-06-01",
        to: "2025-12-31",
        reason: "历史名称记录",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "procurement_supplier",
        contextLabel: "采购选供应商",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 33,
      note: "采购选择时校验能力、资质与业务日期。",
    },
    sensitiveFields: [
      {
        label: "银行账号",
        maskedValue: "6222 **** **** 0188",
        revealToken: "reveal:sup_1:bank",
        visibility: "masked",
      },
    ],
    resourceFacts: [
      { label: "负责人", value: "赵强" },
      { label: "资质预警", value: "正常" },
    ],
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  sup_2: {
    resource: "suppliers",
    stableId: "sup_2",
    stableNo: "SUP-2025-088",
    name: "礼遇包装工坊",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "warning",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 5,
    currentRevision: {
      revisionId: "sup_2_r5",
      revisionNo: 5,
      name: "礼遇包装工坊",
      effectiveFrom: "2025-06-01",
      changeReason: "资质换证提醒",
      actor: "李倩",
      fields: [
        { label: "供应商角色", value: "包装服务" },
        { label: "商务结算版本", value: "v5" },
        { label: "资质", value: "包装服务资质 · 将于 30 日内到期" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "sup_2_r5",
        revisionNo: 5,
        timing: "CURRENT",
        name: "礼遇包装工坊",
        actor: "李倩",
        from: "2025-06-01",
        reason: "资质换证提醒",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "procurement_supplier",
        contextLabel: "采购选供应商",
        eligible: true,
        blockerCodes: [],
        reason: "能力匹配；提交时按业务日期再校验资质",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 12,
      note: "资格由服务端按业务日期计算。",
    },
    sensitiveFields: [
      {
        label: "银行账号",
        maskedValue: "6217 **** **** 5521",
        revealToken: "reveal:sup_2:bank",
        visibility: "masked",
      },
    ],
    resourceFacts: [
      { label: "负责人", value: "李倩" },
      { label: "资质预警", value: "将到期" },
    ],
    allowedActions: ["VIEW", "CREATE_REVISION", "DISABLE"],
    actionBlockers: [],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  sup_3: {
    resource: "suppliers",
    stableId: "sup_3",
    stableNo: "SUP-2024-003",
    name: "旧版物流商（停用）",
    lifecycleStatus: "DISABLED",
    lifecycleStatusLabel: "当前停用",
    lifecycleTone: "neutral",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 1,
    currentRevision: {
      revisionId: "sup_3_r1",
      revisionNo: 1,
      name: "旧版物流商（停用）",
      effectiveFrom: "2024-01-01",
      effectiveTo: "2025-12-31",
      changeReason: "合作终止",
      actor: "赵强",
      fields: [
        { label: "供应商角色", value: "配送" },
        { label: "资质", value: "已失效" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "sup_3_r1",
        revisionNo: 1,
        timing: "CURRENT",
        name: "旧版物流商（停用）",
        actor: "赵强",
        from: "2024-01-01",
        to: "2025-12-31",
        reason: "合作终止",
        isCurrent: true,
        lifecycle: "DISABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "procurement_supplier",
        contextLabel: "采购选供应商",
        eligible: false,
        blockerCodes: ["LIFECYCLE_DISABLED", "QUALIFICATION_EXPIRED"],
        reason: "当前停用且资质已失效",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 9,
      note: "历史采购单引用保留。",
    },
    sensitiveFields: [],
    resourceFacts: [],
    allowedActions: ["VIEW", "CREATE_REVISION"],
    actionBlockers: [
      {
        action: "DISABLE",
        code: "ALREADY_DISABLED",
        message: "对象已停用。",
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  wh_1: {
    resource: "warehouses",
    stableId: "wh_1",
    stableNo: "WH-EAST-01",
    name: "华东一号仓",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 2,
    currentRevision: {
      revisionId: "wh_1_r2",
      revisionNo: 2,
      name: "华东一号仓",
      effectiveFrom: "2025-01-01",
      changeReason: "更新联系人（历史写操作，Q1 后只读）",
      actor: "系统管理员",
      fields: [
        { label: "区域", value: "华东" },
        { label: "SKU 预警策略", value: "安全库存 · 默认" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "wh_1_r2",
        revisionNo: 2,
        timing: "CURRENT",
        name: "华东一号仓",
        actor: "系统管理员",
        from: "2025-01-01",
        reason: "历史维护（Q1 前）",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
      {
        id: "wh_1_r1",
        revisionNo: 1,
        timing: "HISTORICAL",
        name: "华东主仓",
        actor: "导入",
        from: "2024-01-01",
        to: "2024-12-31",
        reason: "首版",
        isCurrent: false,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "warehouse_pick",
        contextLabel: "仓储选择仓库",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 120,
      note: "SKU 策略只生成预警，不改变库存余额。",
    },
    sensitiveFields: [
      {
        label: "联系人 / 地址",
        maskedValue: "周航 · 138****6621 · 上海市浦东新区 ****",
        revealToken: "reveal:wh_1:contact",
        visibility: "masked",
      },
    ],
    resourceFacts: [
      { label: "写权限", value: "本期未确认 · 写操作暂不可用" },
      { label: "策略效果", value: "仅预警，不改库存余额" },
    ],
    warehouseStockSummary: {
      onHandQty: "1,280",
      reservedQty: "42",
      hasBlockingStock: true,
      w10Href: "/inventory?warehouseId=wh_1",
      policyNote:
        "仓库 SKU 预警策略只生成预警信号，不写入或调整库存台账余额/预占。",
    },
    allowedActions: ["VIEW", "EXPORT_ROW"],
    actionBlockers: [
      {
        action: "CREATE",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "CREATE_REVISION",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "DISABLE",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "MAINTAIN_POLICY",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "DISABLE_WITH_STOCK",
        code: "WAREHOUSE_HAS_STOCK",
        message:
          "仓库仍有在库 1,280 / 预占 42，即使 Q1 确认后也不得在有库存时停用。",
      },
    ],
    auditEvents: [
      {
        id: "wa1",
        at: "2026-07-01T10:00:00+08:00",
        actor: "系统",
        action: "写门禁",
        detail: WAREHOUSE_WRITE_CODE,
      },
    ],
    sections: ["overview", "versions", "relations", "audit"],
  },
  wh_2: {
    resource: "warehouses",
    stableId: "wh_2",
    stableNo: "WH-SOUTH-02",
    name: "华南中转仓",
    lifecycleStatus: "ENABLED",
    lifecycleStatusLabel: "当前启用",
    lifecycleTone: "success",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 1,
    currentRevision: {
      revisionId: "wh_2_r1",
      revisionNo: 1,
      name: "华南中转仓",
      effectiveFrom: "2025-06-01",
      changeReason: "启用中转仓",
      actor: "导入",
      fields: [
        { label: "区域", value: "华南" },
        { label: "SKU 预警策略", value: "低周转加强" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "wh_2_r1",
        revisionNo: 1,
        timing: "CURRENT",
        name: "华南中转仓",
        actor: "导入",
        from: "2025-06-01",
        reason: "启用中转仓",
        isCurrent: true,
        lifecycle: "ENABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "warehouse_pick",
        contextLabel: "仓储选择仓库",
        eligible: true,
        blockerCodes: [],
      },
    ],
    usageSummary: {
      historicalReferenceCount: 18,
      note: "策略只读预警。",
    },
    sensitiveFields: [
      {
        label: "联系人 / 地址",
        maskedValue: "陈璐 · 139****3102 · 广州市黄埔区 ****",
        revealToken: "reveal:wh_2:contact",
        visibility: "masked",
      },
    ],
    resourceFacts: [
      { label: "写权限", value: "本期未确认 · 写操作暂不可用" },
    ],
    warehouseStockSummary: {
      onHandQty: "86",
      reservedQty: "0",
      hasBlockingStock: true,
      w10Href: "/inventory?warehouseId=wh_2",
      policyNote: "SKU 策略只生成预警，不改变库存余额。",
    },
    allowedActions: ["VIEW", "EXPORT_ROW"],
    actionBlockers: [
      {
        action: "CREATE_REVISION",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "DISABLE",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "MAINTAIN_POLICY",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
  wh_3: {
    resource: "warehouses",
    stableId: "wh_3",
    stableNo: "WH-OLD-99",
    name: "已封存临时仓",
    lifecycleStatus: "DISABLED",
    lifecycleStatusLabel: "当前停用",
    lifecycleTone: "neutral",
    revisionTiming: "CURRENT",
    revisionTimingLabel: "当前",
    lockVersion: 3,
    currentRevision: {
      revisionId: "wh_3_r3",
      revisionNo: 3,
      name: "已封存临时仓",
      effectiveFrom: "2024-01-01",
      effectiveTo: "2025-03-31",
      changeReason: "清空后停用",
      actor: "仓储",
      fields: [
        { label: "区域", value: "华北" },
        { label: "SKU 预警策略", value: "已停用" },
      ],
    },
    revisionTimeline: buildTimeline([
      {
        id: "wh_3_r3",
        revisionNo: 3,
        timing: "CURRENT",
        name: "已封存临时仓",
        actor: "仓储",
        from: "2024-01-01",
        to: "2025-03-31",
        reason: "清空后停用",
        isCurrent: true,
        lifecycle: "DISABLED",
      },
    ]),
    selectorEligibility: [
      {
        context: "warehouse_pick",
        contextLabel: "仓储选择仓库",
        eligible: false,
        blockerCodes: ["LIFECYCLE_DISABLED"],
        reason: "当前停用",
      },
    ],
    usageSummary: {
      historicalReferenceCount: 3,
      note: "身份保留。",
    },
    sensitiveFields: [],
    resourceFacts: [{ label: "写权限", value: "本期未确认 · 写操作暂不可用" }],
    warehouseStockSummary: {
      onHandQty: "0",
      reservedQty: "0",
      hasBlockingStock: false,
      w10Href: "/inventory?warehouseId=wh_3",
      policyNote: "无库存；写操作仍因本期策略暂不可用。",
    },
    allowedActions: ["VIEW"],
    actionBlockers: [
      {
        action: "CREATE_REVISION",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
      {
        action: "DISABLE",
        code: WAREHOUSE_WRITE_CODE,
        message: WAREHOUSE_WRITE_MESSAGE,
      },
    ],
    auditEvents: [],
    sections: ["overview", "versions", "relations", "audit"],
  },
}

export function resourceLabel(resource: MasterDataResource): string {
  const found = (
    [
      ["sellable-items", "可销售项目"],
      ["products", "商品与 SKU"],
      ["voucher-categories", "卡券类目"],
      ["suppliers", "供应商与资质"],
      ["warehouses", "仓库"],
    ] as const
  ).find(([k]) => k === resource)
  return found?.[1] ?? resource
}

export function computeMetrics(rows: readonly MasterDataListItem[]) {
  return [
    {
      key: "all",
      label: "全部",
      value: rows.length,
      detail: "当前资源",
    },
    {
      key: "enabled",
      label: "当前启用",
      value: rows.filter((r) => r.lifecycleStatus === "ENABLED").length,
      detail: "启停生命周期",
    },
    {
      key: "disabled",
      label: "当前停用",
      value: rows.filter((r) => r.lifecycleStatus === "DISABLED").length,
      detail: "历史保留",
    },
    {
      key: "pending",
      label: "待生效修订",
      value: rows.filter((r) => r.revisionTiming === "FUTURE").length,
      detail: "修订时序 · 非启停",
    },
  ] as const
}
